### ISSUE TITLE
Make Trigger Build Task available to be run on all Platforms

### ISSUE THREAD

**Issue by huserben** [huserben/TfsExtensions#10]
Currently the Task is written in PowerShell. This works fine, as long as the build agent that runs it is a windows machine. On Linux Machines the task will fail with following exception:

---
A supported task execution handler was not found. This error usually means the task does not carry an implementation that is compatible with your current operating system. Contact the task author for more details.
---

In order to make the task run on all agents it has to be rewritten to TypeScript.
When this is done, it should be taken into account that we might want to reuse functionality for a similar task that can trigger releases. (see [Issue 9](https://github.com/huserben/TfsExtensions/issues/9)).

**Comment by tldavies** [comment]
+1 

I am surprised that it let me add the Task and run on a non-windows machine since it is in PowerShell. When I usually add PowerShell scripts it becomes a Demand. Would love to use as this a but we are not only using Window machines.

**Comment by bergmeister** [comment]
@huserben The new version of PowerShell is cross platform: https://github.com/PowerShell/PowerShell

**Comment by huserben** [comment]
Hi

I know about that, but still the proposed way of doing Tasks is with TypeScript according to MS:
"Cross platform tasks are written in Typescript. It is the preferred way to write tasks once."
https://github.com/Microsoft/vsts-task-lib

**Comment by ravikumarjonnadula** [comment]
Hi,

I am trying to use the extension to trigger a build. But even if there is no & in the build definition i am getting the below error.

[error]System.Net.WebException: The remote server returned an error: (400) Bad Request.
2017-07-14T06:26:52.5664574Z ##[error]   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.GetResponse(WebRequest request)
2017-07-14T06:26:52.5664574Z ##[error]   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.ProcessRecord()
2017-07-14T06:26:52.5664574Z ##[error]System.Management.Automation.RuntimeException: Cannot index into a null array.
2017-07-14T06:26:52.5664574Z ##[error]   at CallSite.Target(Closure , CallSite , Object , Int32 )
2017-07-14T06:26:52.5664574Z ##[error]   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
2017-07-14T06:26:52.5664574Z ##[error]   at System.Management.Automation.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
2017-07-14T06:26:52.5664574Z ##[error]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)

Can you please help me out .

**Comment by huserben** [comment]
Hi @ravikumarjonnadula 
next time please open a new issue if you have a problem not related to the topic discussed in this issue.
I moved your question to a new issue: 
https://github.com/huserben/TfsExtensions/issues/17

**Comment by huserben** [comment]
Hi all

just a little update, I started last week looking into the port to node.js so the task will run on all platforms.
It looks good and I hope i can upload a first version in the course of next week :-)

**Comment by huserben** [comment]
Hi all

I uploaded verison 2.0.0 of the Task that is now written in Node and it's possible to use Linux Agents ;-)
See https://marketplace.visualstudio.com/items?itemName=benjhuser.tfs-extensions-build-tasks for the infos
