### ISSUE TITLE
3.0.4: download artifact "error: request timeout"

### ISSUE THREAD

**Issue by daughey** [huserben/TfsExtensions#100]
I think the update to 3.0.4 has introduced a bug in the download artifact functionality :-(

Yesterday our last working build used 3.0.3 and the next build used 3.0.4 and failed to download the artifacts.

![image](https://user-images.githubusercontent.com/19322469/47138627-d5a1df80-d2b1-11e8-8e0a-6ba47651b61a.png)

Is there any more information that you need?

**Comment by huserben** [comment]
Hi @daughey 

sorry for that, I've actually tested the download functionality, however I just have some "dummy" artifacts.
I assume your artifacts folder is a bit bigger (more than just a few KB/MB)?

This is reproducable behavior, meaning it happens everytime you trigger the build?

I have the suspicoun that it's caused by a changed setting I made when looking at the timeout settings related to the other [issue](https://github.com/huserben/TfsExtensions/issues/99).

I can clean this up real quick and provide you a new version asap.

**Comment by huserben** [comment]
I know just uploaded a new version which included the fix that I *think* will solve your issue - can you please give it a try?

If it's not working  I might need a bit more time to figure out what could cause the problem, then it would be good if you could let me know about the size of the artifacts that it's trying to download so I can try to reproduce the issue on my local environment.

**Comment by daughey** [comment]
Yes, a few hundred MBs for some of those  :-) 

I hoped it was just a one off but seven consecutive builds over a timespan of eight hours.

Will give it a go with the new version now and let you know.

**Comment by daughey** [comment]
Almost ... it made it passed the first artifact but failed on the second.

There are four artifacts being downloaded.  The sizes of the artifacts are 220MB, 264MB, 182MB 0.6MB

(Our largest artifact to is about 700MB but we don't use the queue build task to acquire that artifact - we use the OOTB download artifacts task)

![image](https://user-images.githubusercontent.com/19322469/47142616-308c0480-d2bb-11e8-9f39-6f411f76de54.png)

**Comment by huserben** [comment]
Ok, I think I will then change back the actual download request not to go via the retry method, it could be that this has to be treated specially as we actually get a stream back to store the files, unlike the other requests where we will get "plain" json objects back that can be evaluated.

I'll update you as soon as a new version will be available so you could give it a try again.

**Comment by huserben** [comment]
New version is available now, please give it another try. Now the behavior should be exactly as before yesterdays change.

**Comment by daughey** [comment]
Ok. Test build using 3.0.6 is in progress.  Results in about 30 minutes.

**Comment by daughey** [comment]
Success!

Thank you!

**Comment by huserben** [comment]
Very good, sorry again for the inconvenience caused by the issue.

I hope now everything runs smoothly :-)
