### ISSUE TITLE
Triggering a build on a different queue fails

### ISSUE THREAD

**Issue by migheorghe** [huserben/TfsExtensions#102]
Trigger build task fails when the queue specified in task parameter is different than the one the build definition is saved with. 
Bellow is the log. If the triggered build is already saved with the requested Queue it works.
Is this something I am doing wrong or there is a bug in the task?

Thanks,
Mihai

Found id for team project [PROJECT_NAME]: 00541835-7856-4281-95f2-aa1859ebec54
Will trigger build with following demands:
Agent.Name -equals ag016e6e672
Will trigger build in following agent queue: 769
Error during request (1/5)
Error message: Error: No agent pool found with identifier 769.
Error during request (2/5)
Error message: Error: No agent pool found with identifier 769.
Error during request (3/5)
Error message: Error: No agent pool found with identifier 769.
Error during request (4/5)
Error message: Error: No agent pool found with identifier 769.
Error during request (5/5)
Error message: Error: No agent pool found with identifier 769.
##[debug]task result: Failed
##[error]Request failed after 5 tries - see error messages in the log

**Comment by huserben** [comment]
Hi @migheorghe 

thanks for reporting this.
I got a few questions which should help me narrowing the problem down.

- Was this ever working and just started to break lately?  
- If you say if its saved with the requested queue this means that you then don't specify the agent queue in the Trigger Build Task at all?  
- From the logs it looks like you specify directly the id of the Agent Queue, is this correct? Or do you use the name of the Queue and just stripped it from the logs? In case it's the id and not the name, are you certain that this is correct?
You could verify this by going to the Agent Pool overview of your Server Instance, select the desired Agent Queue and check the id in the URL:
![grafik](https://user-images.githubusercontent.com/5486874/47382108-d7303500-d701-11e8-9d87-cdbea8e13f61.png)  
- Last but not least, the triggered build is in the collection/server instance?

**Comment by migheorghe** [comment]
_1)Was this ever working and just started to break lately?_
We never tried it with different queue until Friday
 
_2) If you say if its saved with the requested queue this means that you then don't specify the agent queue in the Trigger Build Task at all?_
We specify the agent queue. This is how we designed the flow in the first place but only lately we needed to change the agent pool of the triggered build.

_3)From the logs it looks like you specify directly the id of the Agent Queue, is this correct? Or do you use the name of the Queue and just stripped it from the logs? In case it's the id and not the name, are you certain that this is correct?_
We specify the id of the agent queue. Because we are triggering a build on a different project in AzureDevOps the id used is the one on that project.

_4)Last but not least, the triggered build is in the collection/server instance?_
The triggered build is on a different project in AzureDevOps

**Comment by huserben** [comment]
Thanks for the reply.

Ok if the triggered build is in the same devops instance and only in a different project, you could once try to specify it via the name, that should actually work.
It should not make a difference but we might get a better log message this way and it could help find and solve the actual problem.

Could you once try this and give me the logs of the result?

**Comment by migheorghe** [comment]
Apparently having the queue specified by name does not work even when the build is on the correct queue.

This is the log when the queue was specified by name but the build was on a different queue
2018-10-25T08:39:43.3385448Z Provided team project was no guid, trying to resolve ID via API...
2018-10-25T08:39:43.7061561Z Found id for team project ProjectName: 12345635-9314-4283-95f2-aa1859eb79cc
2018-10-25T08:39:43.7068206Z Will trigger build with following demands:
2018-10-25T08:39:43.7068661Z Agent.Name -equals NameOfAgent
2018-10-25T08:39:43.7069052Z Build Queue was specified as string: All-Test-x86 - trying to fetch Queue ID for the queue...
2018-10-25T08:39:44.0742451Z No queue found with the name: All-Test-x86. Following Queues were found (Name (id)):

The log with the build on the queue we wanted
2018-10-25T08:41:31.5804766Z Provided team project was no guid, trying to resolve ID via API...
2018-10-25T08:41:31.9392697Z Found id for team project ProjectName: 12345635-9314-4283-95f2-aa1859eb79cc
2018-10-25T08:41:31.9392697Z Will trigger build with following demands:
2018-10-25T08:41:31.9392697Z Agent.Name -equals NameOfAgent
2018-10-25T08:41:31.9392697Z Build Queue was specified as string: All-Test-x86 - trying to fetch Queue ID for the queue...
2018-10-25T08:41:32.3292622Z No queue found with the name: All-Test-x86. Following Queues were found (Name (id)):

**Comment by huserben** [comment]
Ok that helps already a lot in narrowing down the possible causes.
However I won't get even to start looking into it before the weekend.

As soon as there is any update I'll let you know here.

**Comment by huserben** [comment]
Hi @migheorghe 

I was able to reproduce the error in my dev environment.
It seems like the problem is caused by some insufficient privileges when using the OAuth Token Authentication. When asking for the the available Queues none are returned in that case.
It could be that it worked when the specified QueueId was the same as the default queue as it didn't even try to access anything as they were matching already.

Could you give it a try and use a Personal Access Token instead of OAuth and see whether this solves the problem?

**Comment by migheorghe** [comment]
Thanks @huserben, it works with a PAT.

**Comment by huserben** [comment]
Ok, I will with the next version update the documentation accordingly so this limitation is reflected.

Thanks for reporting this, please don't hesitate to create other issues if you find something that is not working as expected or you have a feature request.

**Comment by FelixS90** [comment]
Are there any plans to fix the issue such that this also works with OAuth? PATs may be subject to expiry at some point, which adds maintenance effort.

Thanks a lot!

**Comment by huserben** [comment]
Hi @FelixS90 

I haven't looked any further into the issue. As far as I can tell it's either a problem with the API that it's not allowed somehow or it's about the configuration on TFS/DevOps with the privileges (however I'm no expert in that so I can't really judge...).

At least currently I have no plan in further investigating, as I don't think from the Task side there's much to be done. However if there would be a proposed solution I could potentially take it up and look into it.
