### ISSUE TITLE
Trigger build is failing if JSON needs to be passed as a parameter

### ISSUE THREAD

**Issue by mykolad** [huserben/TfsExtensions#107]
I need to pass a parameter to build definition in JSON. In TriggerBuild task I define additional parameters something like this: TrafficManagerEndpoints: { "a": 50, "b": 50 }

But to build definition this parameter is sent with part after comma cut: TrafficManagerEndpoints={ "a": 50

As the result, I get partial invalid JSON string in my build definition
```
2019-01-30T08:56:50.4820913Z TrafficManagerEndpoints   { "b": 50       
2019-01-30T08:56:50.6509560Z ##[error]ConvertFrom-Json : Invalid object passed in, ':' or '}' expected. (9): { "b": 50
```

Please provide a way to pass JSON parameters to build definitions.

**Comment by huserben** [comment]
Hi @mykolad 

Thanks for reporting this.

This is actually intended behavior, as the parameter string can contain mutliple key value pairs and the behavior so far is splitting the string by "," to divide individual pairs and then by ":" to distinguish between key/variable name and value.

This can be observed when looking at the log with your string:
`2019-01-30T19:22:56.7003847Z Will trigger build with following parameters: 01VarName: TrafficManagerEndpoints: { "a": 50, "b": 50 }`  
`2019-01-30T19:22:56.7753365Z Found parameter 01VarName with value: TrafficManagerEndpoints: { "a": 50`  
`2019-01-30T19:22:56.7753602Z Found parameter "b" with value: 50 }`  

It is briefly described in [here](https://github.com/huserben/TfsExtensions/blob/master/BuildTasks/overview.md#build-parameters) and in detail in the following [issue](https://github.com/huserben/TfsExtensions/issues/54#issuecomment-368578707)

That leaves us with the following options:
- We/you could try to work around this by passing the variables "a" and "b" not in that json format and assemble them within the build itself  
- I could have a look to what could be done, e.g. trying to see whether a "value" is wrapped in curly braces and then treat it specially

However option 2 would definetly need some time as I don't have too much free time on my hands at the moment.

If you have some other ideas or questions please feel free to ask and share

**Comment by mykolad** [comment]
Hi @huserben,

Thanks for the quick answer. I had to go with workaround with option 1 in my case.

It would be great if option 2 would be available as well. As an easy solution probably some way of escaping commas would work. Something like:

TrafficManagerEndpoints: { "a"\: 50\, "b"\: 50 }

**Comment by mykolad** [comment]
Hi @huserben,

As for me, this sounds great. Next week I will be able to test it on my build to confirm the fix.

Thank you for the quick response!

**Comment by huserben** [comment]
@mykolad 

I just uploaded the newest version of the package.
Could you please give it a try with the newest version of the TriggerBuildTask and tell me whether everything works as expected or not?

**Comment by huserben** [comment]
Hi @mykolad 

did you have time to verify the fix?
Please let me know once you did and whether it worked or not.

**Comment by mykolad** [comment]
Hi @huserben 

I was able to check it and it works great. I passed parameters in Trigger Build task advanced configuration in this format:
TrafficManagerEndpoints:{"$(DeploymentUnit)":50, "$(PreviousDeploymentUnit)":50}

And in my build definition they were correctly received as:
TrafficManagerEndpoints:{"a":50, "b":50}

Thank you, the original issue I posted is resolved.

**Comment by huserben** [comment]
Hi @mykolad 

thanks, thats nice to hear.

If you find something else that isn't working as expected or you think could be improved please don't hesitate to open up other issues.
