### ISSUE TITLE
Doesn't work with TFS 2015 On-Premises

### ISSUE THREAD

**Issue by sbarnes921** [huserben/TfsExtensions#11]
I uploaded the tool to our On-Premises TFS 2015 instance, but I don't see the new task type when editing a build definition.  Is this tool compatible with TFS 2015?   What am I missing?

**Comment by huserben** [comment]
Hi
in our office environment we use the Task with a TFS 2015 Update 3 On-Prem Server. I cannot tell you what the exact steps are to install it as I am not responsible for that, but for sure the Task supports it.

**Comment by sbarnes921** [comment]
Yes, I was able to get it to work.  Seems it must have been related to browser cache or something.  Restarting the browser and logging back into our TFS web console did the trick.    It would be nice if the ReadMe, or extensions info mentioned the TFS version compatibility at a glance though.

Thanks!

Steve Barnes | Release Engineer
RealPage
O:612.656.3188  M:612.237.0660  H:952.923.2143

**Comment by huserben** [comment]
Hi
that's true, I added a line in the overview of the Marketplace page that mentiones supported versions. I will upload it with the next version of the Task (I don't want to create a new "release" just to update the overview markdown file...)

Thanks for the input

**Comment by sbarnes921** [comment]
Ok, thank you.

Steve Barnes | Release Engineer
RealPage
O:612.656.3188  M:612.237.0660  H:952.923.2143
