### ISSUE TITLE
Feature for TriggerBuildTask: Only check build conditions from the same branch

### ISSUE THREAD

**Issue by aee11** [huserben/TfsExtensions#110]
We are building build definition A
* If Build In Queue condition is enabled and the blocking build definition is B, then the build is only not triggered if B is queued/in-progress _on the same branch_ (currently other branch builds can block this condition)
* If Successful Dependent condition is enabled and the blocking build definition is B, then the build is only triggered if B is successful _on the same branch_ (currently other branch builds can block this condition)
* I'm not familiar with failed build dependency condition but I suppose that applies as well

So what I'm suggesting is a check box under "Trigger Conditions": "Only check builds on current branch" (or something that is worded better). I'm willing to implement this if you think this makes sense.

**Comment by huserben** [comment]
Hi @aee11 

Thanks for the feedback, this sounds like a meaningful addition.
However I guess it makes only sense to apply this in case you're working with:

1. git repositories
2. the build(s) affected are in the scope of the same repository

So the documentation/help text should be accordingly updated.

I'm planning to make a change for #108 so I could have a look into this also, however timewise this would mean it will be implemented in the next 2-4 weeks (if everything goes according to plan).
If you need it earlier feel free to have a look into it on your own (and let me know if I can assist).

What do you think?

**Comment by aee11** [comment]
Hey @huserben !

Thanks for the fast response. I completely forgot to say thank you for the already great extension. I think your extension is the "missing link" in order to get our monorepo build dependencies setup correctly. So yes, in my case, the builds are in the scope of the same git repository but to keep the trigger mechanism isolated to a certain release branch or the master branch, this feature would be needed.

Maybe it could work for builds in different repositories if there are teams that keep the branch structure similar between repos but I doubt people do that.

There's no time constraint on my side so if you think this can go alongside the fix for #108 then I would be extremely grateful. I'm also willing to grab it but I'm guessing your more familiar with this code base. I looked a bit into the [code](https://github.com/huserben/TfsExtensions/blob/master/BuildTasks/triggerbuildtask/triggerbuildtaskV3/taskrunner.ts#L196) and wasn't sure if I'd have have to look into the `tfsrestservice` package or if you're moving to interacting directly with `azure-devops-node-api`...

**Comment by huserben** [comment]
Hi @aee11 

so I'm finally getting to look into your feature request.
Yeah it could theoretically work with having the same branch structure "by chance", but I think it's best that I'll try to make it clear in the help/documentation that this is inteded for builds within the same git repo (also it's not for anybody using TFVC).

I would propose that we add exactly one checkbox in the condition area that then would apply to all conditions, or would you think we need to be more fine grained and have it on a per condition base?
I would assume there is at least at the moment not a use case where this would be needed?

**Comment by aee11** [comment]
Yes, a single checkbox would be perfect. I can't imagine a use case where
it is needed for each condition.

I look forward to trying this out!

Thanks once again.

**Comment by huserben** [comment]
Hi @aee11 

so I have a working version now of what you suggested. You can specify the option within the Conditions:
![grafik](https://user-images.githubusercontent.com/5486874/60455620-24708900-9c37-11e9-8fa9-f0d48ba9ffcd.png)

Which would cause to filter the respective builds for the same branch:
![grafik](https://user-images.githubusercontent.com/5486874/60455640-381bef80-9c37-11e9-9a35-5759de276e31.png)

In case someone checked it on a TFVC repo it's ignored and logging a warning.

Is this what you would have imagined?

I'll update some dependencies before I would push the new version, so I would still have time to adjust it in case you have some feedback.

**Comment by aee11** [comment]
I just tried it out today and it works perfectly. Thanks for this, truly!

**Comment by huserben** [comment]
Thanks for the feedback, and please don't hesitate to open another issue in case you find any problems or have a proposal for an improvement or also just in case of a question.
