### ISSUE TITLE
Failed request: (401)

### ISSUE THREAD

**Issue by harikrishnanelluri** [huserben/TfsExtensions#112]
##[debug]Processed: ##vso[task.issue type=error;]Failed request: (401)
##[debug]Processed: ##vso[task.complete result=Failed;]Failed request: (401)

**Comment by huserben** [comment]
Hi @harikrishnanelluri 

sorry for the late response, I was on vacation the past weeks and didn't have time to check github.

Does this error happen every time for every build or only in specific scenarios?
Did it ever work for you or did it just start to happen one day? Did you ever try to set the debug parameter to true when queueing the build and check the output then?

Without more details it's hard to reproduce the problem and do further investigation.

**Comment by huserben** [comment]
Closed due to inactivity/not enough information
