### ISSUE TITLE
Cant trigger build

### ISSUE THREAD

**Issue by kobi86** [huserben/TfsExtensions#118]
Hi ,
Just wanted to let you know that when i try to trigger a build using the addon- i get 
"error message: Error: TF215106: Access denied. Project Collection Build Service (XXXXX) needs Queue builds permissions for build pipeline 31:XXXXX in team project XXXXXX to perform the action. For more information, contact the Azure DevOps administrator." 

when doing so from a script - its working

**Comment by kobi86** [comment]
The issue accord both in my end and Microsoft

**Comment by huserben** [comment]
Hi @kobi86 

Thanks for reporting this.

This seems like there is some issue with the authentication, what Authentication method are you using?
It could be that for example if you use a Personal Access Token that the rights associated with this Token has insufficient rights.

**Comment by huserben** [comment]
Closed due to inactivity
