### ISSUE TITLE
Trigger build with specific Source ID

### ISSUE THREAD

**Issue by petermisovic** [huserben/TfsExtensions#119]
Hello, is there any chance ti trigger build with specific Source ID?

**Comment by huserben** [comment]
Hi @petermisovic 

I'm sorry but currently it's not possible to manually specify the source version, only to either queue with the default sources of the same one as the build is being run with.

It could be added but is currently not on the roadmap, so I can't make any promises about if or when it would happen.

**Comment by petermisovic** [comment]
Hello, thanks for update. It would be great update for pipelines. I will stay in track if you would change your mind :) I made it for myself via Powershell script for now

**Comment by huserben** [comment]
Hi @petermisovic 

I published a new version of the task that now supports to select a custom source version:
![grafik](https://user-images.githubusercontent.com/5486874/74609453-53fed380-50ea-11ea-9c42-273954578f78.png)

Could you let me know whether this fulfills your needs and wheter it works as expected or not?

**Comment by dazfez** [comment]
> Hi @petermisovic
> 
> I published a new version of the task that now supports to select a custom source version:
> ![grafik](https://user-images.githubusercontent.com/5486874/74609453-53fed380-50ea-11ea-9c42-273954578f78.png)
> 
> Could you let me know whether this fulfills your needs and wheter it works as expected or not?

Hi @huserben ,

I'm also interested in this fix.
Should that work with a pipeline variable? 

![image](https://user-images.githubusercontent.com/30142020/74666792-0e99df00-519a-11ea-82ee-05b20f88c1a4.png)


I've tried it but couldn't get that to work. If I use the full SHA it works fine

Thanks,

Darren.

**Comment by huserben** [comment]
Hi @dazfez 

It should work with a variable, however according to your screenshot you apply the "Powershell" logic of retrieving this variable :-).

So assuming you have defined a variable named _TargetCommitVersion_ then you should put _$(TargetCommitVersion)_ as value.

Can you try this out and let me know whether it works with that change?

**Comment by dazfez** [comment]
Hi @huserben,

Yes, sorry my mistake. That works fine using _$(TargetCommitVersion)_ .
Thanks again for adding this enhancement to the utility.

Regards,

Darren

**Comment by huserben** [comment]
Hi @dazfez 

Thanks for the verification.
I'll close the issue then, if you or @petermisovic have problems or requests feel free to open a new issue.

**Comment by petermisovic** [comment]
Great, thank you!

**Comment by petermisovic** [comment]
> Hi @petermisovic
> 
> I published a new version of the task that now supports to select a custom source version:
> ![grafik](https://user-images.githubusercontent.com/5486874/74609453-53fed380-50ea-11ea-9c42-273954578f78.png)
> 
> Could you let me know whether this fulfills your needs and wheter it works as expected or not?

I will try and let you know as soon as possible. I have to get rights to install extension in our server.
