### ISSUE TITLE
Unable to download artifacts published by built-in Publish Build Artifacts on Azure DevOps Server 2019

### ISSUE THREAD

**Issue by milliamp** [huserben/TfsExtensions#125]
> This issue is a placeholder issue to track the problem. A fix for the upstream issue is in pull request: https://github.com/huserben/TfsRestService/pull/5 
> Once the upstream issue is fixed, upgrading that package and releasing should fix this issue.

When using the Trigger Build task, and selecting 'Download Build Artifacts' on our Azure DevOps Server 2019 installation, a build artifact published by the built-in 'Publish Build Artifact' task will fail to download the artifacts. 

The agent output shows the following:
```
2020-02-13T03:46:29.8108920Z Waiting for builds to finish - This might take a while...
2020-02-13T03:47:59.9865419Z All builds are finished
2020-02-13T03:47:59.9866058Z Downloading build artifacts to E:\<agentname>\_work\r14\a
2020-02-13T03:47:59.9872033Z Downloading artifacts for Build 67982
2020-02-13T03:48:00.0103967Z Found 1 artifact(s)
2020-02-13T03:48:00.0104710Z Cannot download artifact drop. Only Containers are supported (type is "container)"
```

This is caused by the `TfsRestService` npm package doing a case-sensitive compare on artifactType ("container" vs "Container").

**Comment by huserben** [comment]
Hi @milliamp 

Thank you for reporting this and awesome that you created a PR to fix it right away.
I'll have update the Task accordingly and will publish a the new version as soon as possible - I'll have a look during the weekend and you should have the new version latest on monday.

I will let you know once it's available.

**Comment by huserben** [comment]
Hi @milliamp 

I have now published a new version of the tasks where all use the new version of the tfs rest service that include your fix.

Can you please verify it and let me know whether everything now works as expected? :-)
