### ISSUE TITLE
Using build definition ID rather than name

### ISSUE THREAD

**Issue by ArazAbishov** [huserben/TfsExtensions#126]
First of all, thanks a lot for putting in work to maintain the extension!

The docs specify that build definition name should be used for triggering the builds. Is there a possibility to use build definition ID, which is less prone to changes? 

Thanks!

**Comment by huserben** [comment]
Hi @ArazAbishov 

Thanks for the input.
Yes it's possible, I would suggest the following behavior:
- Treat every input like it's a build definition name (for the unlikely possibility that someone has named his build with only numbers...)
- If we cannot find any build with that name, check whether the specified string is a number
- If it's a number, just use as is

The advantage is that we will not break compatibility and we also don't need to add new configuration options but we can just reuse the existing field :-)

I implemented a version that seems to work fine:
![grafik](https://user-images.githubusercontent.com/5486874/75094349-85641d00-558a-11ea-9fc8-fcdb2d79ea85.png)

I need to do some additional testing but somewhen tomorrow I'll be pushing a new version that should include the change

**Comment by huserben** [comment]
@ArazAbishov 

I published now a new version that contains the change.
Please let me know whether it works as expected.

**Comment by ArazAbishov** [comment]
Thanks for dedicating time to add the feature @huserben, and sorry for the late response. I will test the new version and will come back to you.

**Comment by ArazAbishov** [comment]
Ah, my apologies, I forgot to respond with the feedback. The updated version of the task works really well. Thank you!
