### ISSUE TITLE
Triggering builds from a new branch fail with pipeline is invalid

### ISSUE THREAD

**Issue by jdcurran-git** [huserben/TfsExtensions#128]
This may be just a configuration issue on my end but thought I would ask here first.  I have been using the TriggerBuild now for a while and it has been working great!  Recently we have some new developers on board and they are branching -> doing their work -> then updating the DEV build pipeline to use the branch they created.  Their build will kick off fine and trigger a build of my QA tests but my pipeline fails with - The pipeline is not valid.  Could not get the latest source version for Repository SQA using ref refs/heads/DEV_BRANCH.

I tried googling but found nothing on this.  If I click run pipeline directly it runs fine with no issue.  Any ideas?  Thanks!

**Comment by jdcurran-git** [comment]
I found my problem...  In the advanced section I needed to uncheck the "Use current source version for the current build"  All good now!

**Comment by huserben** [comment]
Hi @jdcurran-git 

is it possible that you setup the trigger build task to use the same source version as the build where it is running in? That could explain the behavior you're experiencing :-)
