### ISSUE TITLE
Waiting for a triggered build throwing an error

### ISSUE THREAD

**Issue by dpharrisplpf** [huserben/TfsExtensions#131]
As of the update on March 21st, waiting for a triggered build throws the following error:
Cannot read property 'definition' of null

Environment:
- Azure Devops 2019 (Onsite)
- I have multiple builds across multiple team projects triggered as a part of this build definition.

This build runs multiple times per day and did not start failing until this update was installed.  I've reverted back to version 1 of the Waiting task and the build executes without issue.

Are any other details needed to support troubleshooting?

Cheers,
Daniel

**Comment by huserben** [comment]
Hi @dpharrisplpf 

I'm sorry to hear that the latest update seem to have broken something.
Could you provide your configuration and also the logs of the task when it's failing?

I ran basic tests before publishing that all succeeded, so it might be a configuration option that went untested.

Can you run other tasks like the trigger build without any problems?

**Comment by huserben** [comment]
Closed due to inactivity
