### ISSUE TITLE
Enhancement: Provide full YAML example

### ISSUE THREAD

**Issue by krispenner** [huserben/TfsExtensions#136]
This is truly amazing, great work!

It would be great if you could expand on your current YAML example and include every possible input. For example, I had to dig into your source code to find the name of the `buildParameters` parameter for use in YAML.

**Comment by huserben** [comment]
Hi @krispenner 

Up to @rfennell PR last week I wasn't even considering yaml much, so there is not much documented yet.

However having an example with *every* possible input might be a bit too big, as you have lots of options. Also you have cases where some inputs can be skipped (e.g. definition of url to the server).

If you use the assistant in the yaml editor you should get all the names of the variables etc.

I could add the yaml definition to the individual inputs in the documentation, that might be a good compromise.
However also that will require some time and it's currently not on the top of my priority list

**Comment by rfennell** [comment]
Wanted to generate Yaml documention for all my extensions, so I wrote my [YAMLGenerator task](https://marketplace.visualstudio.com/items?itemName=richardfennellBM.BM-VSTS-YAMLGenerator) which builds the yaml docs from the manifest files you can use this in the extensions release pipeline.

I have a worked example of my release pipeline [here](https://github.com/rfennell/AzurePipelines/wiki/Outlining-my-Azure-DevOps-CI-CD-Process-using-YAML-based-tools)

Does that help?

**Comment by huserben** [comment]
Hi @rfennell 

that looks awesome, I'll try it out as soon as I can :-)

Many thanks for sharing this 👍

**Comment by rfennell** [comment]
Forgot to point out, look in the yamlgenerators tests for a commented out test harness that allows it to be run outside a release pipeline, it is good for giving it a test locally
