### ISSUE TITLE
Unable to specify git sourceBranch for triggered build

### ISSUE THREAD

**Issue by shmatkotija** [huserben/TfsExtensions#14]
I tried to pass the sourceBranch like so:

Will trigger build with folowing parameters: "sourceBranch" : "testSource"

Which produced:

{ definition: { id: 81 }, sourceBranch: "refs/heads/master", requestedFor: { id: "9bc78cd1-9a57-467b-bed0-77e45442f720"}, parameters: "{"sourceBranch" : "testSource"}"}

**Comment by huserben** [comment]
Hi @shmatkotija 

I uploaded a new version of the task that lets you specifiy the source branch you want to use.
Check under Advanced Configuration, disable the "use same source branch" checkbox and just define the branch you want to use in the textbox below.

For your example this would then just be "testSource".

You can remove the parameters.

Please let me know if this fixed the problem.

**Comment by shmatkotija** [comment]
Thanks! It works great now. One small comment: you have a typo (branchE) in the UX next to the new checkbox.

**Comment by huserben** [comment]
Hi

thanks for the tip, it was late yesterday when I updated the Task :-)
I will fix the typo with the next check in 👍
