### ISSUE TITLE
System.AccessToken certificate has expired

### ISSUE THREAD

**Issue by freyrfinnboga** [huserben/TfsExtensions#141]
Using Azure Devops Server 2019 Update 1 (OnPrem)
Using following Authentication Method: OAuth Token $(System.AccessToken)
Trigger Build task has been working fine past 4 months suddenly (last week) it stopped working with error: certificate has expired

Version of Task being used is
Task         : Trigger Build
Description  : This tasks allows to trigger a new Build (add it to the queue) as part of a Build Definition. It contains as well some conditions that can be applied, for example if the last build of certain definition was successful or not.
Version      : 3.1.7
Author       : Benjamin Huser

Is OAuth tokens no longer supported are we forced to generate PAT tokens with expiration of 1 year?

**Comment by freyrfinnboga** [comment]
Issue was fixed by disable-ing the Intended Purposes from Root certificate AddTrust External CA Root which expired 30.5.2020 for some reason the task was using the older chain even though the new root certificate with same purpose was already on the server

**Comment by huserben** [comment]
Hi @freyrfinnboga 

sorry for the late answer, but good that it cleared itself up.

If you have other problems or questions please feel free to open up another Issue.
