### ISSUE TITLE
JSON Build Parameter Issue

### ISSUE THREAD

**Issue by kaushikmaji** [huserben/TfsExtensions#143]
Hello,

I am using below build parameter:
buildParameters: 'TriggeringProjectName:$(System.TeamProject),serviceprincipals: {"serviceprincipals": [{"name":"adad","endate":"2021-06-16","resourcegroup":"XXXXX"},{"name":"asdad","enddate":"2021-06-16","resourcegroup":"XXXX"}]}'

The pipeline fails as below:
Identified value as Json Object - will use as is
Found parameter serviceprincipals with value: {"serviceprincipals": [{"name":"adad","endate":"2021-06-16","resourcegroup":"XXXXX"},{"name":"asdad","enddate":"2021-06-16","resourcegroup":"XXXX"}]}
Error during request (1/5)
Error message: Error: Could not queue the build because there were validation errors or warnings.
Will wait 1 seconds before retrying request...
Error during request (2/5)
Error message: Error: Could not queue the build because there were validation errors or warnings.
Will wait 2 seconds before retrying request...
Error during request (3/5)
Error message: Error: Could not queue the build because there were validation errors or warnings.
Will wait 4 seconds before retrying request...
Error during request (4/5)
Error message: Error: Could not queue the build because there were validation errors or warnings.
Will wait 8 seconds before retrying request...
Error during request (5/5)
Error message: Error: Could not queue the build because there were validation errors or warnings.
Will wait 16 seconds before retrying request...
##[error]Request failed after 5 tries - see error messages in the log

Do you know how to resolve it?

Regards,
Kaushik

**Comment by huserben** [comment]
Hi @kaushikmaji 

how are the parameters on the target build defined? Are you sure the names are spelled correctly?

The error means essentially that something doesn't match in the target build as far as I can tell.

**Comment by kaushikmaji** [comment]
Thanks Benj for your response. Actually, there was a issue with the target pipeline, it was not working. So I fixed it to resolve the issue and then the triggering worked as expected. Thus the Original issue is resolved.

However, I have another issue. The input JSON parameter value does not work at triggered pipeline, if it does not have spaces. e.g. below failed:

{serviceprincipals: {"serviceprincipals": [{"name":"adad","endate":"2021-06-16","resourcegroup":"XXXXX"},{"name":"asdad","enddate":"2021-06-16","resourcegroup":"XXXX"}]}

but below did:
{ serviceprincipals :  { "serviceprincipals" :  [ { "name" : "adad" , "endate" : "2021-06-16" , "resourcegroup" : "XXXXX" } , { "name" : "asdad" , "enddate" : "2021-06-16" , "resourcegroup" : "XXXX" } ] }

Can you please check?

**Comment by huserben** [comment]
Hi

if you send the json like this the task is actually not doing anything. If there is a problem with the spacing then it's most likely that the Azure DevOps REST API for some reason expects it to be like this. I couldn't tell the actual reason why that is the case though - it's the first time I see it :-)

But your problem is then solved when you use the latter version with the spaces?

**Comment by kaushikmaji** [comment]
Yes Benj, the problem is resolved when I send the JSON with spaces. But thank you for your kind followup and answering me!!
