### ISSUE TITLE
Shelvesets cause error with Get Sources in Triggered Build

### ISSUE THREAD

**Issue by johnphilipscs** [huserben/TfsExtensions#149]
We are successfully using your Trigger build extension to improve our build structure and make reusable build modules.  Thank you for you extension!

However, we would like to us the builds that call the triggered builds for check-ins and if a shelveset is specified and the Get Sources of the triggered build is different from the parent, then the attempt to unshelve fails due to differences in directory structure.  I am not aware of a way to leave Get Sources unspecified so we have the set to the commonly branch but we do check-ins to different branches.

Is this a configuration error on my part, or just not possible to be supported?

**Comment by huserben** [comment]
Hi @johnphilipscs 

From what is possible within the build system itself (leave out steps etc.) I cannot judge. Basically you can pass parameters with the task and if with those parameters you can skip a step it should be supported.

However I'm definetly no expert when it comes to TFVC so I fear I cannot be of much help, sorry.

**Comment by huserben** [comment]
Closed due to inactivity
