### ISSUE TITLE
Trigger Build Task Not Visible

### ISSUE THREAD

**Issue by jaybihola** [huserben/TfsExtensions#150]
We are currently utilizing TFS 2015 (version 14.102.25423.0) and installed the extension. The installation of the extension appears to be successful.

When trying to add a build step, the trigger build task is not in the task list.

Is there any other configuration that is required or did I miss something?

**Comment by huserben** [comment]
Hi @jaybihola 

Did you install version 2.* or 3.*?
I think version 3.* was not compatible with such an old version of TFS, but 2.* might be.

*Edit*: Found another issue that might be related, can you check this out: #120 and see whether that helps you?

**Comment by huserben** [comment]
Closed due to inactivity
