### ISSUE TITLE
Trigger Build pass source branch

### ISSUE THREAD

**Issue by greengumby** [huserben/TfsExtensions#151]
Hi,

Are you able to pass the source branch name through to the triggered build as a variable?

Maybe it does not need to be the branch. I guess it could be build Id

Essentially I have two build pipelines that create artifacts and somehow I need to tell a third pipeline the trigger which builds to pull the artifacts from to use in the DownloadPipelineArtifacts artifacts

Pipeline 1 -> Trigger Pipeline2 (Pipeline1 BuildId) -> Trigger Pipeline 3 (Pipeline1 BuildId, Pipeline2 BuildId)

Thanks

**Comment by huserben** [comment]
HI @greengumby 

yes that should be possible, you have to define the variable (e.g. _Build1ID_ in Pipeline2) and make it settable at queue time.
Then you can pass this variable in Pipeline 1 via the Build Parameters option:
_Build1ID: $(Build.BuildId)_

that should do the trick.
Of course the same goes for the trigger from pipeline 2 to pipeline 3 - you have to create 2 variables and they have to be settable at queue time (depending on whether you use Azure DevOps or a newer version of TFS, this might be called "settable by user" now :-)).

Could you try that out and let me know whether it worked or not?

**Comment by greengumby** [comment]
Worked a treat!

Thanks

**Comment by huserben** [comment]
Awesome!

Please don't hesitate to open up another issue if you are facing a problem, have a feature request or any kind of question.
