### ISSUE TITLE
Feature request: when a build is queued, include a link or the full name of the new build

### ISSUE THREAD

**Issue by shmatkotija** [huserben/TfsExtensions#16]
Currently, when a new build is queued, the name of the definition is included, but nothing that uniquely identifies the queued build. If possible, we would like to be able to get a link to the new build or its full name (which in our case would include the version), so that we can identify it.

**Comment by huserben** [comment]
Hi

this sounds like the issue that was resolved with the latest version:
https://github.com/huserben/TfsExtensions/issues/15

Under Advanced Configuration you have a checkbox that, when enabled, will store the triggered build id into an environment variable.

**Comment by shmatkotija** [comment]
Thanks Ben, I see the ID being printed now as part of the queueing of the build and a message that they were stored in TriggeredBuildIds. However, I can't seem to be able to access that value in any way. I've tried:
$(TriggeredBuildIds), %TriggeredBuildIds%, $TriggeredBuildIds, $env:TriggeredBuildIds.

What I am trying to do is rather than print out just the ID as the task does, print out a link to the newly queued build like so:

https://project.visualstudio.com/myproject/_build/index?buildId=$TriggeredBuildIds

**Comment by huserben** [comment]
Hi,

if you use powershell, you can use the variable like this:
Write-Output "Fetching variable TriggeredBuildIds:"
$variable = [Environment]::GetEnvironmentVariable("TriggeredBuildIds","User")
Write-Output $($variable)

**Comment by shmatkotija** [comment]
Thanks, that works. I was able to print out the link that way. It would be great if it was also part of the task by default.

**Comment by huserben** [comment]
Hi

yeah i can change the output that i will not just print the id but the full link to it.
The storage in the environment variable is basically if someone wants to have additional logic based on this, for example download artifacts or something.

I will change it in the next release of the task that the full link will be displayed then.

**Comment by shmatkotija** [comment]
Thanks Ben!

**Comment by huserben** [comment]
Hi

I just uploaded a new version with your requested change: 
![grafik](https://user-images.githubusercontent.com/5486874/27971242-35d11c8e-6352-11e7-8fdf-ecdded623759.png)

I will close the issue then.

Thanks for your feedback and please keep on raising issues if you find a bug or you have a change- or feature request.
