### ISSUE TITLE
Some "More information" pop-up windows for the Trigger Build task don't have the correct markdown format for hyperlinks

### ISSUE THREAD

**Issue by icnocop** [huserben/TfsExtensions#164]
Hi.

I noticed some "More information" pop-up windows for the Trigger Build task don't have the correct markdown format for hyperlinks.

For example, https://github.com/huserben/TfsExtensions/blob/master/BuildTasks/triggerbuildtask/triggerbuildtaskV3/task.json#L85

 `Please refer to the (documentation)[https://github.com/huserben/TfsExtensions/blob/master/BuildTasks/overview.md#basic-configuration]."`
Should be
 `Please refer to the [documentation](https://github.com/huserben/TfsExtensions/blob/master/BuildTasks/overview.md#basic-configuration)."`
Notice the parenthesis and square brackets.

Thank you.

**Comment by huserben** [comment]
Hi @icnocop 

thanks for the hint, it's fixed now :-)
