### ISSUE TITLE
Trouble with setting "Defines Branch that shall be used" to a release variable

### ISSUE THREAD

**Issue by JaredLane77** [huserben/TfsExtensions#168]
This is a fantastic extension, thank you!
This is working great when I set "Defines Branch that shall be used" to a static branch name, but I'd like to use a variable.
I am creating a Git branch in a previous step using the name of the release: $(RELEASE_RELEASENAME).
This does not seem to be rendering when the task is processed, as the build fails trying to specify that string as the branch name:

#20210326.22   failed           $(RELEASE_RELEASENAME)
#20210326.21   succeeded   Release-16

Is using a variable in this context possible?

Thank you.

**Comment by JaredLane77** [comment]
Sorry, hope no one wasted their time on this, I had the wrong variable name, should be: 

Release.ReleaseName

Thanks!

**Comment by huserben** [comment]
Hi @JaredLane77 

no worries, glad you could figure out so quickly.

In case you have other questions, problems or proposals for improvement please don't hesitate to open up another issue.
