### ISSUE TITLE
Where are the logs?

### ISSUE THREAD

**Issue by harrisonsp** [huserben/TfsExtensions#183]
I've been searching around for where the logs files are written on the Build Agent in response to the message with system debugging enabled. Where are the logs on the Build Agent?

```
Error during request (1/5)
Error message: Error: Could not queue the build because there were validation errors or warnings.
Will wait 1 seconds before retrying request...
Error during request (2/5)
Error message: Error: Could not queue the build because there were validation errors or warnings.
Will wait 2 seconds before retrying request...
Error during request (3/5)
Error message: Error: Could not queue the build because there were validation errors or warnings.
Will wait 4 seconds before retrying request...
Error during request (4/5)
Error message: Error: Could not queue the build because there were validation errors or warnings.
Will wait 8 seconds before retrying request...
Error during request (5/5)
Error message: Error: Could not queue the build because there were validation errors or warnings.
##[debug]task result: Failed
##[error]Request failed after 5 tries - see error messages in the log
##[debug]Processed: ##vso[task.issue type=error;]Request failed after 5 tries - see error messages in the log
##[debug]Processed: ##vso[task.complete result=Failed;]Request failed after 5 tries - see error messages in the log

**Comment by huserben** [comment]
Hi @harrisonsp 

What you've posted are in fact the logs, there is nothing (more) written anywhere on the agent.
`Error: Could not queue the build because there were validation errors or warnings` is coming from the API from Azure DevOps, so nothing from the task directly, so it's hard to judge what is wrong.

Could you provide the complete logs, maybe something can be spotted in the config that can help clear things up.

**Comment by harrisonsp** [comment]
Thanks for getting back to me and for clarifying that the output shown is the log with nothing more written on the agent. The issues coming from the API in Azure DevOps cleared up so we are in the clear now. Love the work you've been doing here!
