### ISSUE TITLE
Question: Build Status Polling on Agents in Scale Sets

### ISSUE THREAD

**Issue by arjankohli** [huserben/TfsExtensions#184]
I'm using this task to trigger a pipeline which runs on a VM Scaleset where the agents seem to be automatically torn down before the task can poll a successful run and see the build triggered completed successfully. Even with a 1 second delay.

I am wondering if this task is implemented so that polling the status of a build can return back success even when the agent it ran on no longer exists. Or if maybe I am encountering some other transient issue in my pipeline, this task, or the tfs rest api it uses. If not I have a few more questions:

- I'm at a loss for options on how to handle the race to read the success status before the agent is deleted unless you have any suggestions on how to confirm the build was successful after the agent is torn down. Unfortunately using a different agent pool is not an option for the pipeline being triggered.

**Comment by huserben** [comment]
Hi @arjankohli 

The polling actually does not depend on the agents, as the build status is stored on azure devops itself. So there should not be any dependency on this.

Could you share some logs of the problem you're getting?

**Comment by huserben** [comment]
Closed due to inactivity
