### ISSUE TITLE
Question: Can we bring back results from triggered pipeline to pipeline where we use Trigger Build task 

### ISSUE THREAD

**Issue by bvrvarma10** [huserben/TfsExtensions#185]
Is there a way to bring back results from triggered pipeline to the pipeline where we use Trigger Build task across different projects within the same organization?
Can we bring the results of the triggered pipeline to the pipeline where we use Trigger build task even when both those pipelines are running on different agents, different projects but on same organization? Please Clarify

**Comment by huserben** [comment]
Hi @bvrvarma10 

The agents which run the build do actually not matter at all. The pipeline information is stored on Azure DevOps and accessible via the REST API (which the tasks are using) - so where it's being run does not matter.

I'm not sure I fully understand what you mean by "bring back results". But if it's about getting the info on whether the pipeline failed or succeeded, this is possible, yes.
You can either use the designated [Wait Task](https://github.com/huserben/TfsExtensions/blob/master/BuildTasks/overview.md#wait-for-triggered-build-task) in case you want to await multiple builds and parallelize things. Or you use the [wait option](https://github.com/huserben/TfsExtensions/blob/master/BuildTasks/overview.md#wait-for-completion-of-triggered-builds) that's built into the main task.

Pipelines of other team projects are also supported, see [Basic Configuration](https://github.com/huserben/TfsExtensions/blob/master/BuildTasks/overview.md#basic-configuration):

> If your build would be in another Team Project, another collection on the same server or a completely different server, uncheck the checkbox and fill in the URL to the server including the collection and the team project

You just have to make sure that whatever authentication method you've chosen has the correct permissions on the other team project.

Does that help?

**Comment by huserben** [comment]
Hi @bvrvarma10 

Did you manage to solve your problem?

**Comment by huserben** [comment]
Closed due to inactivity
