### ISSUE TITLE
Error after new release 3.2.0. A supported task execution handler was not found. 

### ISSUE THREAD

**Issue by Maxim-Krivobokov** [huserben/TfsExtensions#199]
Hello. 
I'm using this extension  on TFS 2018 and on-premises vsts build-agents (windows and linux).
Since last update, I started to have this error on Windows-machines:

`A supported task execution handler was not found. The task does not carry an implementation that is compatible with your current operating system 'Windows'. Contact the task author for more details.`

Is it possible to fix that?

**Comment by huserben** [comment]
Hi @Maxim-Krivobokov 

may I point you to [this issue](https://github.com/huserben/TfsExtensions/issues/200) to discuss the problem, so it's not in 2 different issues.

**Comment by huserben** [comment]
@Maxim-Krivobokov 

The problem should now be solved - see [this post](https://github.com/huserben/TfsExtensions/issues/200#issuecomment-998156943) in the other issue.

Please let me know if it fixed your issue
