### ISSUE TITLE
Can Trigger Build Task trigger an azure pipeline from an azure pipeline?

### ISSUE THREAD

**Issue by dovydasjaru** [huserben/TfsExtensions#201]
I want to know if it is possible to start a different azure pipeline from an azure pipeline. I looked into documentation but could not find a definitive way (if any) to trigger an azure pipeline.

**Comment by huserben** [comment]
Hi @dovydasjaru 

could you elaborate on your use case:
- Is the pipeline in the same team project or in the same organization in a different team project (or in an entirely different organization)?
- What kind of "pipeline" are we talking about? YAML pipeline, "classic" build pipeline or "Classic" Release pipeline?

But in short, I believe unless you are using Release Pipelines the answer is a yes you can do it. Essentially that's what the task is for - triggering other builds from a build (which nowadays is called pipeline :-)).

**Comment by dovydasjaru** [comment]
Hi @huserben 

Thank you for your response.

I was confused about the term "build". Since I could not find any clarifications that build has the same meaning as pipeline. But now I managed to make it work with your extension.

To answer your questions: I was talking about YAML pipeline defined in the same project

Once again, thank you for your answer. And I will close this issue.
