### ISSUE TITLE
Can runtime parameters be passed in as multiline string? (required for object type parameters inside yaml)

### ISSUE THREAD

**Issue by AgileDevOps-ish** [huserben/TfsExtensions#206]
Hi @huserben,

Thanks for building such a cool tool.

Quick question (that I think I already know the answer to).

Is passing a multi-line string as a runtime parameter supported? From what I can see in the code it looks like it's not.

The reason for needing this is because object type parameters in Azure DevOps YAML use this formatting for the elements in the list.

This is how the values would be passed in the GUI at runtime for one element in the list:
![Screenshot 2022-02-07 at 17 59 44](https://user-images.githubusercontent.com/98234730/152855062-47efada2-2eef-4962-b2c8-5f7d74c22472.png)

And this obviously wouldn't work as it would still come out as one line:
![Screenshot 2022-02-07 at 17 58 45](https://user-images.githubusercontent.com/98234730/152854936-ea7cfd7c-9d1f-4f50-9773-c6d5c9efc499.png)

If not currently supported, do you think it could be implemented fairly easily?

Thanks

**Comment by huserben** [comment]
Hi @AgileDevOps-ish 

thanks for bringing up this question. Honest answer is, I don't know, I've never tried. My guess is that currently it's not possible, but that is unconfirmed.

I would also not know exactly how to implement it - in the end the task is just using the rest api and the methods that are exposed by the [azure-devops-node-api](https://github.com/microsoft/azure-devops-node-api).

So if it's supported there, it will probably be simple to make it work via this task. I'm currently not really having much time on my hands, so everything that goes beyond a simple change I will probably not be able to implement myself though.

Another option is always to directly use the REST api (or the mentioned library) if you have a specific use case - If that is needed I might also be able to guide a bit.

**Comment by AgileDevOps-ish** [comment]
Hey @huserben,

Thanks for the prompt reply.

We do have a python script that calls the api and passes those parameters in, however the really nice feature about the tool you've built is that it offers better observability of what the outcome is, as it's embedded within the pipeline, and you can see the successful/unsuccessful outcomes straight into the pipeline. 

With a python script calling the api, it's pretty much fire and forget (there is some error handling in there but it's not as good). The way we do it in the python script is just with a standard multi-line string using """ and azure devops api will just take whatever string you pass it:

![Screenshot 2022-02-08 at 09 55 34](https://user-images.githubusercontent.com/98234730/152963822-3bf0d4eb-f3a5-4758-a787-234a02abf586.png)

![Screenshot 2022-02-08 at 10 00 38](https://user-images.githubusercontent.com/98234730/152964078-7407e186-04ec-4f8a-90e7-468a241c83aa.png)

It looked to me like the way you are handling the templateParameters in the tool is just by processing the input as a normal string, which works fine for normal parameters, but not when you need multi-line params, as it just converts the text to a normal, one line string which then leads to validation errors in the pipeline.

So I guess it's just a matter of ensuring the formatting in the string is kept. For instance when trying to pass in a multiline string to the tool it initally processes it correctly, but then cuts off everything after the new line character, however this works fine in the console.

![Screenshot 2022-02-08 at 10 37 57](https://user-images.githubusercontent.com/98234730/152970792-4ee3a787-d025-4465-8dc9-02db3a57dd9b.png)

![Screenshot 2022-02-08 at 10 38 16](https://user-images.githubusercontent.com/98234730/152970815-9c79dc3c-a3bc-4d29-b6cf-57b53358028c.png)

![Screenshot 2022-02-08 at 10 39 18](https://user-images.githubusercontent.com/98234730/152970903-595d9d2d-11f7-4522-a472-17605b02f92e.png)

**Comment by huserben** [comment]
Thanks for the extensive answer. Is it possible that perhaps the additional ":" as part of the value is causing a problem and not really the newline itself? It happens that this is at the same place...

What you can try is to pass the complete json object that should be sent. There you won't have as many restrictions as with the "regular" syntax, but you have to make sure all the escaping etc. is done correctly. As the doc states:

> An exception to the rules above is if the value is a complete Json object, this will be treated specially. For example the following will be allowed:
> 01VarName: { "a": 50, "b": 50 }, 02VarName: { "Value1": 12, "OtherObject": { "SomeValue": 13, "Child": { "Name": "MyChild" } } }

> If you are constrained by the above mentioned rules, you can also specify the exact json object that will be used. For this just include the whole object and make sure to encapsulate it in "{ }". Note: If you're using this option, you have to make sure that the escaping of the values etc. is handled correctly.

So for your example, it could end up looking somehow like this:

`templateParameters: "Environments: { ... }"`

**Comment by AgileDevOps-ish** [comment]
Thanks, will try that.

When using the JSON notation, do the {} get passed into the actual value? That would be an issue as those characters should not be in the final value passed to azure devops.

**Comment by huserben** [comment]
No they should not get passed. It's just a workaround to not apply any "cleanup" but be able to specify the parameters in a "raw" json format for some special cases. So I think it's worth a try at least.

**Comment by AgileDevOps-ish** [comment]
Thanks, will give it a go.
