### ISSUE TITLE
Expose `TriggeredBuildIds` as multi-job/stage variable

### ISSUE THREAD

**Issue by ChristoWolf** [huserben/TfsExtensions#208]
Hi @huserben!

Your [Trigger Build Task guide on the VS marketplace](https://marketplace.visualstudio.com/items?itemName=benjhuser.tfs-extensions-build-tasks) specifies for the `TriggeredBuildIds` variable, that
> The variable is as well available as an input in the configuration for _any_ subsequent Task.

However, unless I missed something, this only holds true for tasks in the same job.

I'll try to propagate the variable as a multi-job variable on my own for now, but I think it would be useful if it was exposed to the whole build in general by default or through an option.

**Comment by ChristoWolf** [comment]
Hi @huserben!

Thanks for the quick reply!

One then still also has to inject the variable into the job then, but yes, that is exactly what I have done.
Works perfectly fine, I just thought to let you know that the guide might be misunderstood.

Anyways, thanks for these great extensions, very useful stuff!

**Comment by ChristoWolf** [comment]
Hi @huserben!

Thanks for the quick reply!

One then still also has to inject the variable into the job then, but yes, that is exactly what I have done.
Works perfectly fine, I just thought to let you know that the guide might be misunderstood.

Anyways, thanks for these great extensions, very useful stuff!

**Comment by huserben** [comment]
> One then still also has to inject the variable into the job then, but yes, that is exactly what I have done.

What exactly do you mean by "inject into the job"?
As I think what could be done is to make the powershell code I posted part of the task, but you would still need to reference it via the same way in the next job, I think no way to work around this.

**Comment by ChristoWolf** [comment]
Sorry for being unclear.
The output/multi-job variable cannot simply be referenced in follow-up jobs without injection via expressions.
It needs to be [set/injected accordingly](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#set-variables-by-using-expressions) to be usable.

**Comment by huserben** [comment]
Sorry for the long wait, I missed that you answered so fast :-)

Yes, I think there is no other way (technically from Azure Pipelines), or is there? :-)

I'm planning on creating a new version in the near future, so what I could do is the following:
- Make sure we set `TriggeredBuildIds` as output variable so it can be referenced by following jobs
- Update the docs to specify how to use it in other jobs

Am I missing something or would you expect something else?

Thanks for your support

**Comment by ChristoWolf** [comment]
Hey @huserben!

No worries, you responded quickly anyways :)

IMO, the first change regarding the automatic propagation as an output variable is not really needed.
That would make built-in Azure Pipelines behavior hidden as magic in your task, and I think explicitness would be better here, i.e. that the consumer needs to manually promote the variable, as they also need to then inject it into their job of choice.

However, I do absolutely agree that the docs should reflect this, i.e. that the consumer needs to make explicit use of Azure Pipelines' usual multi-job/multi-stage variables mechanism to use `TriggeredBuildIds` outside of the current job/stage.

But these are just my opinions, of course feel free to disagree/agree wherever :)

**Comment by huserben** [comment]
Hi @ChristoWolf 

I just published a new version of the task with an updated documentation. I took the very easy road and more or less added your statement from above together with links to the docs from microsoft and this issue:
![Mulit-Job Variable Usage Doc](https://user-images.githubusercontent.com/5486874/155838116-5448b099-e3bb-477f-a705-6549684475cc.png)

Do you think this will be sufficient? Or should something else be added?

Thanks for your support.

**Comment by ChristoWolf** [comment]
Hi @huserben!

Thanks for all the quick effort, very appreciated!

The doc addition looks great, the only I thing I think would still make sense to change/update would be the usages of `available to all following tasks` (paraphrasing), as that might still be a bit misleading when not reading the full doc.

But again, please feel free to disagree!

Also, thanks for listing me as a contributor in the release, really wasn't necessary, but I appreciate it :)

**Comment by huserben** [comment]
Hi @ChristoWolf 

thanks for spending time on a sunday to give me feedback. You are right, I did not think about adjusting this, but it certainly makes sense.
I'll update this soon. Sadly the docs (on the marketplace) are only updated with a new release, so technically I have to release a new version with just the doc change - I'm not sure whether I should do this or just have it "bundled" with the next set of changes - I'll leave the issue open till I've updated the docs in github at least and made a decision on whether I release a new version or not.

I do highly appreciate people taking the time to write here in order to improve the task, this will help others using the task as well. So most certainly you (and everyone else raising issues) is contributing and therefore deserves a mention :-)

**Comment by ChristoWolf** [comment]
Hi @huserben!

Well, sorry for disrupting your weekend!
Sounds great, thanks again!

**Comment by huserben** [comment]
Hi @ChristoWolf 

finally found the time to do some pending updates of the documentation.

I've now added it like this:
![image](https://user-images.githubusercontent.com/5486874/201469749-3d4b855a-2a80-4a0a-baf7-e4f5c3e0f01a.png)

I hope that makes it a bit more clear for the readers in future. Do you think it's fine now and we can close this issue or do you see other things that are still pending?

**Comment by ChristoWolf** [comment]
Sounds perfect, thanks @huserben!
