### ISSUE TITLE
Failed builds do not upload an artifact

### ISSUE THREAD

**Issue by johnqa** [huserben/TfsExtensions#209]
Hi,

I am using this task in a Release, in order to trigger some builds that execute different kind of tests. 
I use the functionality to download the build artifacts but this does not work when the build is failed due to failing tests (that fail tasks inside the build).

This is an issue because I cannot retrieve the results of tests executions.

Thank you,
John

**Comment by huserben** [comment]
Hi @johnqa 

Yes downloading artifacts currently is only supported if the build that is triggered did not fail. You could setup the triggered builds not to fail on a failing test but instead mark it as "partially successful". Then you can setup the trigger build task to treat partially successful builds as successful and then download the artifacts.

I _think_ that could work, so maybe you can give this a try?

**Comment by johnqa** [comment]
Hi,

I have tried your suggestions but without success.

First of all for some tools and ways of executing tests there is no option (at least that I know of) to make the task not fail so this cannot apply.

Secondly the other option to not fail the task if the triggered build fails, does not allows to have the artifact downloaded. The check box for download artifact is only visible if "Fail the build if the tasks were not successful" is checked.

Thanks for having a look.

**Comment by huserben** [comment]
Ok, sorry I was not aware that I've set it up like this.

I'm planning on creating a new version in the coming days, so I could remove that check. However it would of course be "use at your own risk" as the artifacts might not be available if the build fails (so whatever artifact you need you must make sure they are uploaded). I don't plan on adding any extensive error handling, so if the artifacts are not available I assume it will fail.

Would that work for you like that?

**Comment by johnqa** [comment]
Hi, it would be great like that.

**Comment by huserben** [comment]
Hi @johnqa 

I've uploaded a new version of the task that removes the constraint - now artifacts can be downloaded as long as we're waiting for the build to finish, but independent of the builds success.

Would you please let me know whether this works for you now?

Thanks for your help.

**Comment by johnqa** [comment]
Hi, 
It works nicely, thank you.

**Comment by huserben** [comment]
@aequitz as far as I can recall, yes.
