### ISSUE TITLE
[error]Git checkout failed with exit code: 128

### ISSUE THREAD

**Issue by PartySky** [huserben/TfsExtensions#21]
I have 2 projects: Rox.Cache and Rox.Tools.

I added Trigger Build task to Rox.Tools project and setted Rox.Cache project as Build Definition.

![2017-08-05 18 37 45](https://user-images.githubusercontent.com/30129799/28997087-45458ac0-7a0d-11e7-8fca-2dda39c5b386.png)

The Rox.Tools builds well:

![2017-08-05 18 40 13](https://user-images.githubusercontent.com/30129799/28997127-e23021ba-7a0d-11e7-8678-b287d95192e8.png)

After Rox.Tools building I go to Rox.Cache building logs and see thet  Rox.Cache build failed:

![2017-08-05 18 44 59](https://user-images.githubusercontent.com/30129799/28997166-4847610c-7a0e-11e7-8f18-961a3c813b98.png)

The error is: `[error]Git checkout failed with exit code: 128`

l see, that for some reason both projects have same hash `7991e8a36297d20824d34c92b7be8d1d44fce618`

But when I build Rox.Cache without Trigger Build task, this project builds well without any issues and Rox.Cache project has another hash `3c82d0688910e90ef27d2ed43ad8be2834636278`:

![2017-08-05 18 52 56](https://user-images.githubusercontent.com/30129799/28997217-5def01e4-7a0f-11e7-978a-7675b73a48dd.png)

**Comment by huserben** [comment]
Hi @PartySky 
can you maybe post the output of the TriggerBuildTask that triggered your 2nd build?

**Comment by huserben** [comment]
Hi @PartySky 
any progress on your Problem?

**Comment by huserben** [comment]
I really can't help you without any more information, will close the issue for now, could be reopened once you get back to me.
