### ISSUE TITLE
Trigger automated test cases after executing release pipeline

### ISSUE THREAD

**Issue by dadiaz18** [huserben/TfsExtensions#213]
I have two repositories (See the structure below)

> Organization A

     Project A 
          Repo A  (Front End Repository with React)
     Project B 
          Repo B  (Automated Test Cases)

After the creation of a new release in the QA environment using release-pipeline for Project A - Repo A, I need to trigger automated test cases (Project B - Repo B), both in the same organization within Azure DevOps.
Is it possible to use this extension for this purpose?

Do I need to have something more like an API to use this extension?
Thanks!

**Comment by huserben** [comment]
Hi @dadiaz18 

> I need to trigger automated test cases (Project B - Repo B)
If by triggering test cases you mean a pipeline in Project B, yes you can do that. You **cannot** trigger releases though.

Check the [Basic Configuration](https://github.com/huserben/TfsExtensions/blob/master/BuildTasks/overview.md#basic-configuration) for the explanation how this works.

Also there are some things to be aware of when you are triggering something that is in a different repo/team project. Please see [Important Configuration Options when Triggered Build is not located on the VSTS/ADO/TFS Instance or Team Project](https://github.com/huserben/TfsExtensions/blob/master/BuildTasks/overview.md#important-configuration-options-when-triggered-build-is-not-located-on-the-vstsadotfs-instance-or-team-project)

**Comment by huserben** [comment]
Hi @dadiaz18 

Did you manage to trigger your build or do you need some support?

**Comment by dadiaz18** [comment]
Hi, huserben, for the moment I suspended this task because I have other priorities, I will resume this in a couple of weeks I think thanks for asking.

**Comment by huserben** [comment]
Ok thanks for the reply.

I'll close this issue then. In case the documentation/above links don't help you can reopen the issue.

**Comment by dadiaz18** [comment]
Ok Thanks huserben!
