### ISSUE TITLE
BUG: All my scheduled builds using the 'Trigger Build' task started failing last night / yesterday

### ISSUE THREAD

**Issue by GordonRudman** [huserben/TfsExtensions#214]
Error during request (5/5)
Error message: Error: VS800075: The project with id 'vstfs:///Classification/TeamProject/53ab994c-2253-49b5-9c0d-e686ae9d1222' does not exist, or you do not have permission to access it.

It's interesting that the first target build actually gets triggered/run, but the 'Trigger Build' task fails, reporting that it couldn't find the target build, which is very strange (because it just ran it).

I was running v3, but I also tried using v4 as a workaround, but that failed too.

**Comment by huserben** [comment]
Hi @GordonRudman 

as I have not changed anything lately that issue is probably related to some "environmental" change rather than the task itself. Maybe something on your azure devops instance has changed?

**Comment by GordonRudman** [comment]
Ah, OK.
I haven't changed anything recently either, so I'm guessing Microsoft must have then.

**Comment by huserben** [comment]
Are the errors persistent, meaning if you run the pipelines again, does it still fail?

I googled the error and found that others seem to face it as well and that it seems to be related to some permission that changed (without people having changed it themselves...):
> Hi Merry Meng, we were having exactly the same issue since today. Downloading artifacts in other projects' release pipelines used to work.  
I can confirm that your suggestion to add the Project Build Service Account to Build Administrator group with View permission works.  
Can you please explain what changed recently and why this permission is now required?  
Note that the project hosting the release pipeline has Limit job authorization scope to referenced Azure DevOps repositories turned off. I believe there is a bug which crept in recently.

[https://developercommunity.visualstudio.com/t/error-vs800075-when-downloading-artifact-from-anot/1146258](https://developercommunity.visualstudio.com/t/error-vs800075-when-downloading-artifact-from-anot/1146258)

So perhaps this would be an option to check out?

**Comment by huserben** [comment]
@GordonRudman 
is the problem still happening for you or did it resolve itself (which could mean it might have been a temporary problem, perhaps related to Azure DevOps)?

**Comment by GordonRudman** [comment]
I'm on the road at the moment, so can't really check it properly, but it seems to have resolved itself 😊

Thanks for having a look into the problem, and thanks for creating this very useful utility.
