### ISSUE TITLE
No option to Carry Build Number from previous Build to the triggered build

### ISSUE THREAD

**Issue by amitdnets** [huserben/TfsExtensions#215]
No option to Carry Build Number from previous Build to the triggered build. Can you please suggest who this can be done.

I have tried a way to declare a variable in the section "Define additional template parameters for the build" as the following:

**followed_build_number: $(build.buildnumber)**

But in the triggered build how can I retrieve the value of this variable **followed_build_number**.

**Comment by huserben** [comment]
Hi @amitdnets 

If you want to pass a variable/template parameter to another build, you must specify it in the triggered build and then pass it.
You can check https://github.com/huserben/TfsExtensions/issues/182 for a similar case and description on how it got solved.

Please let me know if you managed or need additional support

**Comment by huserben** [comment]
@amitdnets 

Any updates on this from your side?
