### ISSUE TITLE
Designate the resource to use in the pipeline

### ISSUE THREAD

**Issue by bw5io** [huserben/TfsExtensions#219]
Hi,

Thank you for your extension. This really helped us a lot!
I was wondering if the extension can designate the resource to use during the pipeline. Is there a way to do that for now?

**Comment by huserben** [comment]
Hi @bw5io 

could you elaborate what exactly you mean by "deisgnate the resource to use"?
Is it about which specific agent is running the triggered pipeline?

**Comment by bw5io** [comment]
Hi @huserben ,

Thanks for the swift reply. No it's not.

In the YAML Pipeline there's a portion called resource which could be used to specify a pipeline or commit or stuff to get artifact / commit / version throughout the pipeline. We use resource because it would be easier for devs to choose the build run which includes the artifact they want in the azure devops interface. However we're also calling the same pipeline from other pipelines. Currently I don't know if I can specify resource using the plugin. I'm curious if there's a way to do that.
