### ISSUE TITLE
Trigger Build - queueid does not seem to have an effect

### ISSUE THREAD

**Issue by swerve92** [huserben/TfsExtensions#222]
Hi

Trigger Build used to work fine for us, but we didn't use it for a while and now when I try to use it I have noticed the triggered builds are running on the wrong agent pool (the default one).

When Trigger Build is run, its log contains the following:

Will trigger build in following agent queue: 244
(244 is the correct id for the agent pool that I want the build to run on)

But when I follow the link for the queued build and I check the agent pool, it is just being queued on the default pool for the build defintion.

**Comment by huserben** [comment]
Hi @swerve92 

any update on this?
