### ISSUE TITLE
Trigger release pipelines?

### ISSUE THREAD

**Issue by virmitio** [huserben/TfsExtensions#223]
It's not readily apparent to me from the documentation, can `TriggerBuild` task be used to trigger and wait on a release pipeline or only build pipelines?  Trying to sequentially chain a pile of existing build and release pipelines in a reliable fashion.

**Comment by huserben** [comment]
Hi @virmitio 

it is not possible to trigger release pipelines with this task.

**Comment by virmitio** [comment]
Is this a conceivable feature for the future?  I'd be very interested to see it, or an alternative task with behavior similar to `TriggerBuild` that triggers and waits upon a release.

Trying to work around my current problem, if I run a `TriggerBuild` task and pass `waitForQueuedBuildsToFinish` as true, is there a variable being set in the calling pipeline that will give me the build/run ID of the build I just triggered?

**Comment by virmitio** [comment]
Found what I was looking for in the docs, as `TriggeredBuildIds`

In some future revision, it would be handy to include in the docs a code block with a YAML listing a complete set of possible input parameters and a concise list of outputs/variable produced.  Or to have this kind of complete canonical example in a file of the repo, with a link to it from the docs.

Leaving this issue open for now, as the first question of my previous comment is still relevant to the original issue topic.

**Comment by huserben** [comment]
Hi @virmitio 

sorry for the late reply, somehow I've missed the notification emails.

Yes I'll try to provide a more extensive yaml example next time I'll publish a new version. I'd update this issue once I have something ready.

Thanks for raising this.

**Comment by huserben** [comment]
I've finally published a new version and now included a link to the following file in the docs:
https://github.com/huserben/TfsExtensions/blob/master/BuildTasks/yaml_examples.md

There are yaml examples for the 3 different tasks.

Do you see anything missing or can I close this issue now?

**Comment by huserben** [comment]
Closed due to inactivity
