### ISSUE TITLE
triggered build pipeline finishes in warning, but parent pipeline was not successfull

### ISSUE THREAD

**Issue by vicente-espinha** [huserben/TfsExtensions#251]
I created a build pipeline "B", which uses the task "Trigger Build" (version 3)  to trigger multiple pipelines. Sometimes one of the triggered pipelines finished in "Warning" and the pipeline "B" finished in "Failed" with an error like "pipeline x was not successful". 

Why is this the case? Shouldn't it continue the pipeline "B"'s execution when the triggered pipelines are not failing (only in "Warning")?

Please let me know if you need more details about this issue.

**Comment by huserben** [comment]
Hi @vicente-espinha 

if a pipeline has warnings, it's "partially successful". As stated in the [docs](https://github.com/huserben/TfsExtensions/blob/master/BuildTasks/overview.md#wait-for-completion-of-triggered-builds), you can treat them as "successful". The default is that partially successful is causing an error, but you can override this behavior.

Please let me know if that solved your problem.

**Comment by vicente-espinha** [comment]
Hi @huserben 
It "partially" solved the issue :smile: . It was happening a strange behaviour. The build pipeline is represented in the image below. The task "A" triggers multiple pipelines, including the one which finished in "warning". 
![image](https://github.com/huserben/TfsExtensions/assets/22790772/b7789702-8999-420c-93ee-e6d6eeb58988)
This task had the following advanced configurations:
![image](https://github.com/huserben/TfsExtensions/assets/22790772/55c622d0-54ad-47e5-a8b1-460faac90586)
So, as you said, task "A" is successful, but (I do not know why) task "B" fails because it does not have the "Treat a Partially Succeeded Build as Successful" checked. It fails on a build definition which was triggered by task "A". Why does this happen?

Note: I tested adding the "Treat a Partially Succeeded Build as Successful" configuration to tasks "B" and "C" and solved the issue, but I do not understand why 🤷‍♂️

**Comment by huserben** [comment]
Ok, this is indeed interesting.

I think what's happening is this:
- Task A triggers pipelines and awaits them
- the "Store triggered build id's in a variable" is set for Task A, so it populates the variable
- Task B triggers pipelines and awaits them
- As there are already "IDs" stored in the variable, it's appending the newly triggered ones
- Task B then checks *all* pipelines, including the ones triggered by Task A
- As Task B has "Treat partially succeeded" turned off, and the pipeline triggered by A is checked and has a warning, Task B fails

So to solve this, you can treat them as successfull as you did, but this might have unintended side effects (if you don't want to accept partially successful pipelines triggered by Task B). The other, and I think cleaner, option would be: Simply "uncheck" the "Store triggered build id's in a variable" for Task A (and potentially also the other tasks).

More info on this in the [docs](https://github.com/huserben/TfsExtensions/blob/master/BuildTasks/overview.md#store-build-ids-in-variable):

> If any subsequent task needs the info of which builds were triggered by this Task, this information is available as an environment variable to the subsequent Tasks. The name of the variable is TriggeredBuildIds. If more than one build will be triggered, the values will be written comma separated. If there is already a value in the variable from a previous Task, it not overwritten but keep the original value and append his resulting build id's.

Can you try this out and see if it solves your problem?

Thanks for raising this!

**Comment by vicente-espinha** [comment]
Yes, it works! Now, tasks "B" and "C" do not fail.

Thank you for your time and support!
