### ISSUE TITLE
Error: Could not queue the build

### ISSUE THREAD

**Issue by Shivanky-ms** [huserben/TfsExtensions#252]
We have a pipeline where we are using [template parameters](https://learn.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/parameters-parameter?view=azure-pipelines) in complex json format (object type) with default values
When we are running the pipeline from another pipeline using this task

        - task: TriggerBuild@4
          displayName: 'Trigger xyz Pipeline'
          inputs:
            buildDefinition: 'xyz pipeline'
            useSameBranch: false
            branchToUse: 'master'
            storeInEnvironmentVariable: true
            authenticationMethod: 'OAuth Token'
            password: abc
            failTaskIfBuildsNotSuccessful: true
            cancelBuildsIfAnyFails: true
          
We are getting below error:
         
        Provided team project was guid.
        Context is Build - using Build Environment Variables
        Build shall be triggered for same user that triggered current build: Shivanky Goyal
        Error during request (1/5)
        Error message: Error: Could not queue the build because there were validation errors or warnings.
        Will wait 1 seconds before retrying request...
        Error during request (2/5)
        Error message: Error: Could not queue the build because there were validation errors or warnings.
        Will wait 2 seconds before retrying request...
        Error during request (3/5)
        Error message: Error: Could not queue the build because there were validation errors or warnings.
        Will wait 4 seconds before retrying request...
        Error during request (4/5)
        Error message: Error: Could not queue the build because there were validation errors or warnings.
        Will wait 8 seconds before retrying request...
        Error during request (5/5)
        Error message: Error: Could not queue the build because there were validation errors or warnings. 

We don't want to pass 'templateParameters' from this pipeline, because we want to pick parameters that are set as default, how can we do that?

**Comment by Shivanky-ms** [comment]
When we are running this pipeline with parameters from another pipeline with task TriggerBuild@4 without passing any parameters, it is not picking default parameters.

**Comment by huserben** [comment]
Hi @Shivanky-ms 

yes, this I got. But as mentioned, I'd need some context, as when I try it, I don't get any errors:
> Is the task you shared complete or are there more configuration options?
Was the task ever running for you? In this or other configurations?

When you say it's not picking the default parameters, does it mean the pipeline runs, but not with the default ones? Because in the initial issue, you posted an error message where I assumed the pipeline wasn't running at all. How does it exactly behave? If it triggers the pipeline, what parameters is it running with if not the default?

I'd love to support you, but for that I'd need more information.

**Comment by Shivanky-ms** [comment]
Thanks @huserben,
Yes pipeline with parameters is not running at all and pipeline with task TriggerBuild@4 failed with below error:
    Provided team project was guid.
    Context is Build - using Build Environment Variables
    Build shall be triggered for same user that triggered current build: Shivanky Goyal
    Error during request (1/5)
    Error message: Error: Could not queue the build because there were validation errors or warnings.
    Will wait 1 seconds before retrying request...
    Error during request (2/5)
    Error message: Error: Could not queue the build because there were validation errors or warnings.
    Will wait 2 seconds before retrying request...
    Error during request (3/5)
    Error message: Error: Could not queue the build because there were validation errors or warnings.
    Will wait 4 seconds before retrying request...
    Error during request (4/5)
    Error message: Error: Could not queue the build because there were validation errors or warnings.
    Will wait 8 seconds before retrying request...
    Error during request (5/5)
    Error message: Error: Could not queue the build because there were validation errors or warnings.

**Comment by huserben** [comment]
@Shivanky-ms 
can you share the complete yaml of the task you're using as well as the header with the template parameters of the pipeline you are triggering?

Also is the pipeline in the same organization, and if yes, within the same team project?
Lastly, which version are you using? Azure DevOps or Azure DevOps Server? If Server, which exact version is in use?

**Comment by Shivanky-ms** [comment]
Pipeline1.yaml:

    trigger: none
    
    parameters:
      -name: timeout
        type: number
        default: 1
  
      -name: level1Timeout
        type: number
        default: 2
    
      -name: level2Timeout
        type: number
        default: 3
    
      -name: "test"
        type: object
        default:
          -parentTest: a
            areas:
              -component: c
                initial: 'abc@gmail.com'
                level1: 'abc@gmail.com'
                level2: 'abc@gmail.com'
    
          -parentTest: b
            areas:
              -component: d
                initial: |
                  abc@gmail.com
                  def@gmail.com
                level1: |
                  abc@gmail.com
                level2: 'abc@gmail.com'
              -component: e
                initial: 'abc@gmail.com'
                level1: 'abc@gmail.com'
                level2: 'abc@gmail.com'
   
    stages:
      -${{ each comp in parameters.test }}:
          -stage: ${{ comp.parentTest }}
            displayName: ${{ comp.parentTest }}
            dependsOn:
            jobs:
              -job:
                displayName: ${{ comp.parentTest }}
                pool:
                  name: pool-test
                  vmimage: 'ubuntu'
                steps:
                  -script: echo ${{ comp.parentTest }}
          -${{ each area in comp.areas }}:
              -template: ./templates/testTemplate.yaml
                parameters:
                  parentTest: ${{ comp.parentTest }}
                  component: ${{ area.component }}
                  initial: ${{ area.initial }}
                  level1: |
                    ${{ area.initial }}
                    ${{ area.level1 }}
                  level2: |
                    ${{ area.initial }}
                    ${{ area.level1 }}
                  timeout: ${{ parameters.timeout }}
                  level1Timeout: ${{ parameters.level1Timeout }}
                  level2Timeout: ${{ parameters.level2Timeout }}

Pipeline2.yaml:

        -task: TriggerBuild@3
          displayName: 'Trigger Pipeline1'
          inputs:
            buildDefinition: 'Pipeline1'
            useSameBranch: false
            branchToUse: 'main'
            storeInEnvironmentVariable: true
            authenticationMethod: 'OAuth Token'
            password: pwd
            failTaskIfBuildsNotSuccessful: true
            cancelBuildsIfAnyFails: true
            
When we run Pipeline2, we get above mentioned error. Our requirement is Pipeline2 should run Pipeline1 with default parameters.

**Comment by Shivanky-ms** [comment]
Received same error with version 4

**Comment by huserben** [comment]
Ok thanks for adjusting.
The only other thing that sticks out is the "useSameSourceBranch" setting.
Can you once try with the setting set to "true" instead and see if that helps? Just to narrow down on what the problem might be.

**Comment by Shivanky-ms** [comment]
Thanks @huserben , it is working fine with useSameSourceBranch: true
Our requirement is to use some other branch, can you please help with resolution for useSameSourceBranch: false?

**Comment by huserben** [comment]
Thanks for checking.
That basically means that the value you provided was not correct. 

I can see it's setup like this:
`branchToUse: 'main'`

Does a branch named "main" exist? Because the API gives us a validation error and that means it's not finding that branch. If you are certain that main (written exactly like this) exists, you could also try "refs/heads/main" as an alternative.

**Comment by Shivanky-ms** [comment]
Thanks a lot @huserben , this was the issue, we are using branch name in which pipeline2.yaml does not exists.
We can mark this issue as resolved.

**Comment by huserben** [comment]
Great @Shivanky-ms , will close the issue then
