### ISSUE TITLE
TriggerBuildTask Feature Request: Queue Multiple Builds with Unique Parameters

### ISSUE THREAD

**Issue by aequitz** [huserben/TfsExtensions#257]
# Queue Multiple Builds with Unique Parameters
The current implementation supports queuing multiple builds at once and waiting for all builds to complete. This is great because it can greatly reduce the amount of agents required to run just for waiting for the triggered builds to complete. However, it would be great if we could also specify unique values for all of the parameters that get passed into the `triggerBuild` function shown below.

![image](https://github.com/user-attachments/assets/6075db8c-92b5-4d93-9c36-8d78607dc071)

**Comment by huserben** [comment]
Hi @aequitz 

thanks for your input. Let me start by saying that I'm not planning to actively develop further features right now, as I'm focusing on other topics.

Anyway, I'm curious to understand better what you mean. At the moment you can queue several builds in multiple steps, and just have a single "wait" task at the end, that waits for all builds to be completed. That way you can specify unique parameters for every build. If you want to trigger different pipelines with different parameters, I believe the configuration will be quite messy. So having this in a dedicated task that you can run after each other made more sense to me.

Could you elaborate on your scenario a bit more in detail to make sure I fully understand it?

**Comment by aequitz** [comment]
I had not realized that you also have a task that waiting for builds to complete. This should actually work well with what I’m trying to accomplish. Thanks for the quick response! Good with closing this one out.

**Comment by huserben** [comment]
Ok, glad this solves your problem. Feel free to reach out/create an issue if you face some problems with this (or anything else for that matter).
