### ISSUE TITLE
Wait for build to finish error

### ISSUE THREAD

**Issue by Serdfd** [huserben/TfsExtensions#32]
Hi, I am trying to use this extension and the trigger task work great, but when I add the "Wait for Build(s) to finish" always get the next error:

**Cannot read property 'split' of undefined**

I didnt change anything in the configuration, just change Authentication method to OAuth Token.

Hope you can help me.
Thanks.

**Comment by huserben** [comment]
Hi

did you store the triggered build id in the variable? that's an option of the trigger task under advanced configuration.

**Comment by Serdfd** [comment]
Oh, I didnt know about that option, my bad... its works know :)
Thanks for your replay and your work!

**Comment by huserben** [comment]
Hi

ok very good.
l will leave the issue open until I added a better check inthe task that will produce a better error message.
