### ISSUE TITLE
Version 2.4.4 has broken build

### ISSUE THREAD

**Issue by patnolan** [huserben/TfsExtensions#42]
Hi,

TFS has just auto updated to version 2.4.4 of the Trigger Build task and now our production build is failing with the error 

"error: The value specified for Shelveset is not valid."

Note:
Use current changeset for triggered build is set to false
Use same source branch as triggered build is set to false
Defined Branch to use is "Dev"

Please can this be resolved ASAP as we can no longer build!

**Log output**

******************************************************************************
Starting: Trigger a new build of e5ContentStorage Release
******************************************************************************

Task         : Trigger Build
Description  : This tasks allows to trigger a new Build (add it to the queue) as part of a Build Definition. It contains as well some conditions that can be applied, for example if the last build of certain definition was successful or not.
Version      : 2.4.4
Author       : Benjamin Huser
Help         : 

Using current Team Project Url
Path to Server: http://e5tfs.dataract2.local:8080/tfs/dataract/e5 Releases
Trying to fetch authentication token from system...
Using OAuth Access Token
Build shall be triggered for same user that triggered current build: Patrick Nolan
Will trigger build with following parameters: \"BuildVersion\":\"3.9.8654\",\"BuildConfiguration\":\"release\",\"BuildPlatform\":\"any cpu\"
Build in Queue Condition is enabled
Current Build Definition shall be included
Following builds are blocking:
e5Workflow Release
Checking if blocking builds are queued
Checking build e5Workflow Release
None of the blocking builds is queued - proceeding
Queue new Build for definition e5ContentStorage Release
Could not queue the build because there were validation errors or warnings:
error: The value specified for Shelveset is not valid.
Could not Trigger build. See console for more Information.
******************************************************************************
Finishing: Trigger a new build of e5ContentStorage Release
******************************************************************************

**Comment by huserben** [comment]
HI @patnolan 

You said:  Defined Branch to use is "Dev" - how did you define this? I don't see that that anywhere in the logs.

The error is coming from TFS/VSTS itself when we try to queue a build, however I can't determine right now why it's trying to find a shelveset as I don't see anywhere something mentioned in the logs and you don't even use the "use same source version".

Can you maybe post the logs after you set the debug parameter to true?

**Comment by patnolan** [comment]
Hi @huserben,

I set the branch to 'Dev' via the "Defines Branch that shall be used" field. This has been working until now.

I've attached the log files for you. Just let me know if you need more info.

[logs_8661.zip](https://github.com/huserben/TfsExtensions/files/1582166/logs_8661.zip)

**Comment by huserben** [comment]
ok thanks for the quick feedback.

Just checking your settings and what was changed in the last version I cannot identify what possibly broke it (the change from 2.4.3 to 2.4.4 was really minor and should just have affected the "use same source version" property).

I'm looking into it now and try to recreate the same behavior on my environment. I will come back to you as soon as I have more info.

**Comment by patnolan** [comment]
Thanks @huserben heaps for your help it's greatly appreciated. 

I'm assuming we had 2.4.3 before as I only installed the extension a few months ago. Unfortunately TFS automatically upgraded and now I can't be 100% sure what the previous version was.

**Comment by huserben** [comment]
If you have "old" builds you could check the logs, when running the Task the version is printed out.

So I checked on my environment, when I specifiy a different branch it properly triggers and and it's running fine.
I even tried with a non-existing branch and even this works fine from the build that runs my task, so it's then failing afterwards when running the queued build itself (because of course the branch its trying to get the sources from does not exist).

However that doesn't really help in figuring out the problem I'm afraid :-(

Just to make sure, you are using git and not TFVC right?

**Comment by patnolan** [comment]
Hi @huserben,

I had a look at a previous successful build and sure enough is was 2.4.4. Strangely there were no changes made to the definition between the build that failed and succeeded. 

So I  uninstalled and re-installed the extension and it's working again.

Weird! But to be honest I'm just happy our prod build is working again.

Thanks heaps for your prompt help. I'm a big fan of this extension.

**Comment by huserben** [comment]
hmm ok, well I think then I'll close the issue for now.

Please come back to me if you experience the same thing again or you have another issue or feature request, I'm happy to help.
