### ISSUE TITLE
Build Trigger failing for paths

### ISSUE THREAD

**Issue by JeffRausch** [huserben/TfsExtensions#51]
I'm trying to send a folder path as an additional parameter but The BuildTrigger keeps failing.
I'm using VSTS with my own local build agent on a Windows 2016 server.  Here's the value of the additional parameters field:
`\"BuildOutTarget\":\"E:\\Build.Out.Debug\"`
I tried it without escaping the backslash in the path but then it gets a JSON format error and if I remove that variable or even change it so it's not a path then it executes the build correctly.
Here is the log output when I try to run it using the above value:

`[section]Starting: Trigger a new debug build for all projects`
`Task         : Trigger Build`
`Description  : This tasks allows to trigger a new Build (add it to the queue) as part of a Build Definition. It contains as well some conditions that can be applied, for example if the last build of certain definition was successful or not.`
`Version      : 2.5.5`
`Author       : Benjamin Huser`
`Help         : `
`TF400898: An Internal Error Occurred. Activity Id: d5b75a65-c55c-4901-97fb-a3287a0a3de4.`
`Using current Team Project Url`
`Path to Server: {REMOVED}`
`Using Personal Access Token`
`Build shall be triggered for same user that triggered current build: {REMOVED}`
`Using same branch as source version: refs/heads/master`
`Will trigger build with following parameters: \"BuildOutTarget\":\"E:\\Build.Out.Debug\"`
`Queue new Build for definition TestProject1`
`Request Body: {"definition":{"id":31},"sourceBranch":"refs/heads/master","requestedFor":{"id":"386cf5e8-e7b9-660d-9bab-b8a9075d1811"}, parameters: "{\"BuildOutTarget\":\"E:\\Build.Out.Debug\"}"`
`[error]Could not Trigger build. See console for more Information.`
`[section]Finishing: Trigger a new debug build for all projects`

Any ideas of a workaround for this type of issue?

**Comment by huserben** [comment]
Hi @JeffRausch 

I think this is related to the issue reported here as the build parameters are not properly escaped:
https://github.com/huserben/TfsExtensions/issues/47

Once this is fixed I would say you could try again and check if your problem is solved. Otherwise We have to have a deeper look into it.

**Comment by huserben** [comment]
Hi @JeffRausch 

I just uploaded the version 2.6.0 of the task which should include a fix for your problem. Can you please update it and let me know whether it solved your issue or not?

**Comment by JeffRausch** [comment]
Works great now!  Without this extension we wouldn't have been able to move to VSTS so thanks a ton!
