### ISSUE TITLE
Dependent Build Timestamp Not Updated

### ISSUE THREAD

**Issue by bdwellborn** [huserben/TfsExtensions#6]
Our setup is 1 VSTS project with 1 Git repository that contains multiple projects (Project A and Project B).  Upon successful build of Project A it kicks off build for Project B.  Upon successful build of both projects only the first build (Project A) is updated to indicate that it has been run.  In other words, the first build (Project A) says it was requested 1 minute ago, but the dependent build (Project B) still says 4 days ago.

Is there a way to configure so that both builds show an accurate build timestamp?

**Comment by huserben** [comment]
Hi @bdwellborn 
so the build actually runs but something is not updated or it actually doesn't run at all?
Where do you see this "old" timestamp exactly? Can you maybe provide me some demo VSTS project where I can see this behavior?

Thanks for your feedback

**Comment by bdwellborn** [comment]
I have attached a couple screen captures showing the information, hope it helps.  Let me know if you need more.
[VSTS-Timestamp-Issue.pdf](https://github.com/huserben/TfsExtensions/files/984925/VSTS-Timestamp-Issue.pdf)

**Comment by huserben** [comment]
Hmm so if the build really was run then this seems to be more of an issue related to VSTS itself.
The task really just triggers the build via the API provided by VSTS, everything that happens then is outside of the tasks influence...
Can you maybe show the log of the build that should kick of the 2nd build?

**Comment by bdwellborn** [comment]
I have attached the log from the Trigger build.
[VSTS_Trigger_Log.txt](https://github.com/huserben/TfsExtensions/files/987968/VSTS_Trigger_Log.txt)

**Comment by bdwellborn** [comment]
I just noticed that it looks like the issue is the view I am looking at because it looks to be showing my builds.  The build of the first was manual from me, but the other was invoked from the successful build of the first. The build of the second is showing to be initiated by a different user than me.  It looks like this is a user error, do you agree?

**Comment by huserben** [comment]
Yeah i think then the problem is at least not that crucial.
Even though it would be nice in my opinion if the build that is triggered would be for the same account that triggered the initial one. I think implementing this should be possible, but that's not on the top of my priority list right now...
But once this is done your problem should be fixed then as well.

**Comment by bdwellborn** [comment]
Would you mind providing an estimate for when you might be able to get to this?  Our team likes your extension but are concerned about this.

**Comment by huserben** [comment]
I might have some time over the weekend to look into it, if so i should be able to at least have a clue about what it means to implement

**Comment by huserben** [comment]
Turns out it was quite simple :-)
I just uploaded Version 1.7.0 that should include the necessary changes. Now you find under "Basic Configuration" a flag that you can set that the user that triggered the original build will be used for the triggered build as well (it is enabled by default).

Please check if this solves your issue and let me know

**Comment by bdwellborn** [comment]
That is great news, thank you!  I will get with the team to get it updated and let you know the results.

**Comment by huserben** [comment]
Hey @bdwellborn 
do you have any update on this issue?

**Comment by bdwellborn** [comment]
Yes, the update did resolve the issue.  Thank you!
