### ISSUE TITLE
Harden "wait for builds to finish" task?

### ISSUE THREAD

**Issue by cdacamar** [huserben/TfsExtensions#63]
We sometimes see an issue where long running trigger builds will sometimes return us back `ECONNREFUSED` or `ECONNRESET`.  Is there a way to implement some kind of retry or mechanism to handle general network errors?

**Comment by huserben** [comment]
Hi

seems like a similar problem as https://github.com/huserben/TfsExtensions/issues/59
I'll try to have a look and see what I can do.

**Comment by huserben** [comment]
Hi @cdacamar 

I uploaded version 2.8.0 of the task just now which includes some, hopefully, improved error handling of the get requests made to the server. Basically it now tries up to 5 times before it fails for good.

I plan on closing this issue as the same issue is discussed in the linked issue. Please give me a quick feedback in the other issue if you see improvement or if it didn't help so I could continue investigate.

**Comment by cdacamar** [comment]
Thank you!  We were having many builds fail due to this issue.

**Comment by huserben** [comment]
No problem. Please let me know once you see whether the change helped or not. It's quite hard for me to verify the fix as I was not able so far to recreate the issue.
