### ISSUE TITLE
"Fail the build" option will fail for partially successful triggered tasks

### ISSUE THREAD

**Issue by burndeal** [huserben/TfsExtensions#64]
When "Fail the build if the tasks were not successful" is enabled, it will fail even for partially successful tasks.

This is either a bug (since the triggered task didn't fail), or there should be an option to "Pass the build if tasks were partially successful".

Steps to reproduce:
1. Create "BuildA" that has a failing task, but configure it to "Continue on Error"
2. Create "BuildB" and trigger "BuildA".  Configure it to fail if BuildA fails.
3. Execute "BuildB" and it will fail.

**Comment by huserben** [comment]
Hi @burndeal 

I was so far never thinking about Partially Successful builds, thanks for the input.
I think I'll add an additional option to the task that will allow you to continue and not fail even for the partially succeeded ones.

I'll let you know here once the task is updated. Thank you for your input.

**Comment by huserben** [comment]
Hi @burndeal 

I uploaded version 2.8.0 just now which includes a new option to treat partially successful builds as succesful, so the task won't fail.
![grafik](https://user-images.githubusercontent.com/5486874/38459209-55343e62-3aa7-11e8-9c0d-c0ff581253b0.png)

Please give it a try and let me know whether its fine like this or if it needs further change.

Thank you very much for your participation in improving the Task. In case you find a bug or have other improvements in mind please don't hesitate to open other issues.
