### ISSUE TITLE
Source Version Label

### ISSUE THREAD

**Issue by patnolan** [huserben/TfsExtensions#69]
Hi,

I have a TFS Build Definition (lets call it MasterBuild) which uses your Trigger Build task to build 3 separate Build Definitions in the appropriate order.

When I queue MasterBuild I need to use the Source Version field to specify a Label.

How do I pass this label to the Trigger Build task so all 3 Build Definitions build using the same Label?

**Comment by huserben** [comment]
Hi @patnolan 

If you specified a label or changeset via the source version, you can use the "Use Current Changeset" option under advanced configuration to queue the triggered builds with the same option:
![image](https://user-images.githubusercontent.com/5486874/39423979-d6f58ef4-4c74-11e8-9722-8bb7891a47c5.png)

**Comment by huserben** [comment]
Hi @patnolan 

were you able to try it out with my suggestion?

**Comment by huserben** [comment]
Hi @patnolan 

just trying to check in whether you were able to check on the "Current Changeset" option?

**Comment by huserben** [comment]
Closed due to inactivity.

In case of any response it can be reopened.
