### ISSUE TITLE
Can you use Trigger Build with just VSTS and Github?

### ISSUE THREAD

**Issue by JDCurran** [huserben/TfsExtensions#71]
Hi!

I am trying to trigger a VS MSTest solution build after dev deploys.  I have the trigger at the end of the deploy and I keep getting authentication error with TFS.  The issue is we do not use TFS.  We are VSTS and Git.   Is there a way to get around this?  It looks like the plugin is using TFS API so I am guessing that is why it cannot log in.  Thanks!

**Comment by huserben** [comment]
Hi @JDCurran 

the task works with both TFS and VSTS.
Did you read through the section ***Authentication Options*** on https://marketplace.visualstudio.com/items?itemName=benjhuser.tfs-extensions-build-tasks?
What kind of authetentication did you setup?

**Comment by JDCurran** [comment]
Yes, I have read through that and also checked the issue one person had with authentication failure.  I tried using Oauth but get authentication failed message - It says it can not log into TFS which we do not use.  That is what led me to believe it would not work for me.

**Comment by JDCurran** [comment]
OK so I am slapping myself right now :-).  All I had to do was check off the enable scripts access - BINGO!  Thanks so much!  This is awesome stuff here :-).

**Comment by huserben** [comment]
If it helps, it happened to me as well more than once already :-)

If you happen to have another question, find a bug or a proposal for improvement of the tag, please don't hesitate to open another issue.
