### ISSUE TITLE
execute builds across multiple build server

### ISSUE THREAD

**Issue by cnlmason** [huserben/TfsExtensions#73]
does this extension have the capability to run builds on more than one build server?

**Comment by huserben** [comment]
Hi @cnlmason 

could explain in more detail what exactly you mean by running builds on more than one server?
Is it about "parallelizing" a single build definition?

**Comment by cnlmason** [comment]
I have configured your extension to run a series of 8 builds.

The first 3 builds run on server A

The next 2 builds  run on server B

The last three builds run on Server C

Make sense

Chuck Mason
651-795-5485

**Comment by huserben** [comment]
Yes, this is supported. If you want to queue a build of another server you just have to manually specify the address and team project the build is in.
Furthermore as authentication option you can only use a Personal Access Token or Basic Authentication when the build is not located on the same server instance that triggers it. These things have then to be setup on the target server.
Please as well refer to the description under https://marketplace.visualstudio.com/items?itemName=benjhuser.tfs-extensions-build-tasks. Especially the part under Basic Configuration that covers the _Important Configuration Options when Triggered Build is not located on the VSTS/TFS Instance or Team Project_.

Let me know whether it worked or not with the configuration described.

**Comment by huserben** [comment]
Hi @cnlmason 

were you able to solve your problem with the documentation provided?

**Comment by huserben** [comment]
Hi @cnlmason 

ok, so in that case can I close the issue as it seems to be resolved for you?
