### ISSUE TITLE
VSTS Vnext build is not getting trigger when it is scheduled

### ISSUE THREAD

**Issue by yellesh12** [huserben/TfsExtensions#74]
Hi Team,

I have vnext build definition which should trigger the trigger a new build task. when i do it manually it is working fine when i schedule it through the task scheduler it is not working.

Note : The task schedular job is there in the build server this will trigger the build and post that it will initiate the vnext build contains test cases  the vnext definition is getting trigger but trigger a new build task is not getting trigger.

Please look into it as soon as possible.

Thanks,
Yellesh

**Comment by huserben** [comment]
Hi @yellesh12 

so you have a build definition that uses my Task. And when you queue a build of that definition manually it's working fine. And when you have a sheduled build it's not working? Do I get that right?

Can you send me the log files of the Task when for the case where it's not working?

**Comment by yellesh12** [comment]
2018-05-25T23:12:52.3209939Z ##[debug]Sending Request to following url:
2018-05-25T23:12:52.3209939Z ##[debug]build/builds?api-version=2.0&ignoreWarnings=true
2018-05-25T23:12:52.3209939Z ##[debug]Request Body: {"definition":{"id":664},"sourceBranch":"","requestedFor":{"id":"3b3c7538-8f4d-478c-86b2-f70e061ec86e"},"sourceVersion":"C185110"}
2018-05-25T23:12:52.3989284Z ##[debug]task result: Failed
2018-05-25T23:12:52.4079198Z ##[error]Bad Request
2018-05-25T23:12:52.4079198Z ##[debug]Processed: ##vso[task.issue type=error;]Bad Request
2018-05-25T23:12:52.4119177Z ##[debug]Processed: ##vso[task.complete result=Failed;]Bad Request


![image](https://user-images.githubusercontent.com/39619584/40600444-1a79ac36-626f-11e8-80da-095b390d3d4e.png)

**Comment by huserben** [comment]
Hi

could you as well post me configuration of the Task?
The difference between whether you trigger it manually and scheduled however might be the user it is requested for. So if the "scheduled user" does not have the permissions to queue that build definition it could explain the behavior.

Is the build that shall be triggered in the same team project on the same server?
Is it needed that the build that is triggered is for some the same user? To verify the suspicion, you can uncheck the "Queue Build for user that triggered original build" box under basic configuration and see what happens for a manually triggered build. If the box is not checked, the Requested For parameter will be determined depending on what kind of Authentication method you've selected.

**Comment by huserben** [comment]
Hi @yellesh12 

any update on your issue?

**Comment by huserben** [comment]
Will close the issue due to no follow up by poster.
