### ISSUE TITLE
Build parameters for "Trigger Build Tasks" are undocumented

### ISSUE THREAD

**Issue by PxlBuzzard** [huserben/TfsExtensions#77]
Neither the [test file](https://github.com/huserben/TfsExtensions/blob/637695a34b3af4172120e39472b33d0b05f43b01/BuildTasks/triggerbuildtask/tests/taskRunnerTests.ts#L244) nor the [helpMarkDown](https://github.com/huserben/TfsExtensions/blob/637695a34b3af4172120e39472b33d0b05f43b01/BuildTasks/triggerbuildtask/task.json#L216) give a hint as to how to format the build parameters.

**Comment by huserben** [comment]
Hi @PxlBuzzard 

the build parameters are bit more complex so I was not able to properly describe that in the help markdown. But as it says in the Build Task Description it is described on how it can be used. However a link might help in the markdown.

With the documentation provided under https://marketplace.visualstudio.com/items?itemName=benjhuser.tfs-extensions-build-tasks are you able to use the field?

**Comment by PxlBuzzard** [comment]
That gives a great description, thank you! I found the extension through the VSTS Marketplace which doesn't link to the full description as far as I can tell.

A link in the markdown and a test case that covers the issue you linked to in the description would probably both be good quick changes going forward. Thank you for everything you've built so far!

**Comment by huserben** [comment]
Ah ok, then it's definetly not ideal as it is at the moment. As I'm usually not reading/giving much attention to the help markdown of my tasks this is a bit of a blindspot for me, thanks for pointing that out.

I will check all the existing help markdowns and update them if needed.
Thanks as well for the proposal of adding a test case for the issue, I will see what I can do.

I'll leave this issue open until I made the changes and uploaded a new version that includes them. However as I don't deem it to be of super high priority, so it might take a bit till I get to it.

**Comment by huserben** [comment]
Hi @PxlBuzzard 

I uploaded a new version (2.9.2) which should include an update on the help markdowns where I thought it makes sense to extend. Now the help markdown looks as follows:
![grafik](https://user-images.githubusercontent.com/5486874/43655122-fe36d0bc-974d-11e8-8bbf-f5129195384c.png)

Regarding the test case, the actual handling of the parameters is implemented in a service I'm using for more than one extension, therefore the tests would belong there. I added an issue and will try to take it up when I find the time: https://github.com/huserben/TfsRestService/issues/2

I hope that's fine with you, I'll close the issue. If something is not ok, please let me know.

In case you have other findings please don't hesitate to open a new issue here on github.
