### ISSUE TITLE
Add more secure options for storing authentication information

### ISSUE THREAD

**Issue by heikkoe** [huserben/TfsExtensions#82]
Is it possible to instead of storing and worse so, showing, the tokens and password instead point the build def to use a variable group with secrets?

**Comment by huserben** [comment]
Hi @heikkoe 

How do you mean storing and showing?
You can always use a variable that is set to secret and reference this, if you mean that. It is shown in the screenshot in the documentation how to do that:
https://github.com/huserben/TfsExtensions/blob/master/BuildTasks/overview.md#personal-access-token

Please let me know if this was your question or if I missunderstood you.

**Comment by heikkoe** [comment]
The docs indeed help. I suggest adding the variable hint to field labels as currently in the task itself there is no hint that you can actually use variables instead of just storing a plain text password or pat there.

**Comment by huserben** [comment]
That is true, thank you for the suggestion.
I will take this up in the next version so hopefully other people won't have the same problem.

I will close the issue once the version that includes the change is uploaded.

Thanks very much for helping to improve the task, please don't hesitate to open up another issue in case you find a bug or have some suggestions for improvement.

**Comment by huserben** [comment]
Hi @heikkoe 

I uploaded a new version of the tasks that include now in the help markdown a reference that tokens should be written down as a (secret) variable and accordingly referenced:
![grafik](https://user-images.githubusercontent.com/5486874/43655244-5c39393e-974e-11e8-8e8e-afe959caccd2.png)

I hope that prevents any confusion in the future.
Thanks again for reporting this.
