### ISSUE TITLE
Task doesn't work anymore.

### ISSUE THREAD

**Issue by BlackSlashProd** [huserben/TfsExtensions#86]
Hi,

Since this morning our builds are broken because the task "Trigger Build Task" seems doesn't working properly.
A message say "This task is no longer installed. Re-install the task or remove it from your definition." even if task is installed. I tried to uninstall / reinstall, disable/enable... nothing works.

When I try to add a new task with type "Trigger Build Task" it doesn't appear in the list of installed task.
When I go in "manage extension" it seems well installed and activated.

Something was broken in the last version of yesterday ?

**Comment by huserben** [comment]
Hi @BlackSlashProd 

yes I know, I'm sorry for the trouble. I just uploaded a new version that should fix it so it is again the way it was before my last update yesterday.

Please let me know whether it's back to normal for you with that version.

**Comment by BlackSlashProd** [comment]
Thank you for the fix and for your reactivity.

It works very well now.

**Comment by JordanRBG** [comment]
Hi @huserben 

We are also encountering the same issue with our on-premise version of TFS 2018; are we best just re-installing the extension to resolve the issue?

Thanks.

**Comment by Wazner** [comment]
@huserben Thank you for your quick response. You're doing a great job here and the support is even quicker than most paid support 👍

**Comment by JordanRBG** [comment]
@huserben 
Thanks for the fix, our tasks are now working as expected in TFS.
