### ISSUE TITLE
Newly installed 3.0.0 is not visible in the task list

### ISSUE THREAD

**Issue by sandeep10n** [huserben/TfsExtensions#87]
Hi,
We upgraded to your latest package 3.0.0. 
Still it is not listed in the available task list. Can you please suggest the possible root cause and solution.

![tasknotvisible](https://user-images.githubusercontent.com/32562006/43708113-54b5b972-9987-11e8-85a8-19ac4d454a8a.png)

BR,
Sandeep

**Comment by huserben** [comment]
Hi @sandeep10n 

it should be fixed with the newest version 3.0.1.
Please refer to [Issue 86](https://github.com/huserben/TfsExtensions/issues/86) which addresses the same problem.

**Comment by sandeep10n** [comment]
Thanks for quick reply :)

but we are not able to see 3.0.1

can you please share the link ?

**Comment by huserben** [comment]
It should be available normally over the marketplace side:
https://marketplace.visualstudio.com/items?itemName=benjhuser.tfs-extensions-build-tasks

If you need the package as vsix, you can find it here in the repo:
https://github.com/huserben/TfsExtensions/blob/master/BuildTasks/Releases/benjhuser.tfs-extensions-build-tasks-3.0.0.vsix

Please let me know if you managed to solve the issue :-)

**Comment by huserben** [comment]
HI @sandeep10n 

I'm sorry, in my hurry I accidentally posted the wrong link to the release package. I actually didn't upload it to the repo yet, sorry for that. Here is the correct link:
https://github.com/huserben/TfsExtensions/blob/master/BuildTasks/Releases/benjhuser.tfs-extensions-build-tasks-3.0.1.vsix

I hope you could make it work by now, sorry again for the mess
