### ISSUE TITLE
TFS throws error since Trigger Build Task version 3.0.2 was released

### ISSUE THREAD

**Issue by patnolan** [huserben/TfsExtensions#88]
TFS now throws error since Trigger Build Task version 3.0.2 was released

Error is "This task is no longer installed. Re-install the task or remove it from your build definition"

Should we reinstall Task?

**Comment by huserben** [comment]
Hi

which version of which task did you have installed that is causing the issue? I installed it yesterday on my VSTS instance and did not face a problem

**Comment by patnolan** [comment]
Hi @huserben we were using version 3.

Our build failed last night. Now when I open the build definition I see the errors in attached screenshot.

I assume it is related to latest task upgrade.

![image](https://user-images.githubusercontent.com/21251166/43755664-4e091128-9a54-11e8-9e04-87dfb4b142cf.png)

**Comment by huserben** [comment]
Hi

hmm that is odd, if you add new tasks, can you find any of the following:
TriggerBuild, Wait for build or Cancel Build?

I wonder if the update somehow didn't go through well and nothing is installed or something else went wrong

**Comment by evamueller** [comment]
@huserben 
thank you, reinstalling solved the problem and the settings were retained.

**Comment by patnolan** [comment]
Hi @huserben I can also confirm that uninstalling and reinstalling solved the problem and the settings were retained.

This is a great community project and very much valued. Keep up the good work!

**Comment by huserben** [comment]
@evamueller , @patnolan 
Ok very good, I hope it didn't cause too much trouble for you.

I'll close this issue then, please feel free to open another issue if you have any problem, question, or suggestion for improvement.
