### ISSUE TITLE
Installing Trigger Build .vsix in TFS causes Error: XML Document- 'public' is not a valid value for global::Microsoft.VisualStudio.Services.Gallery.WebApi.PublishedExtensionFlags.

### ISSUE THREAD

**Issue by jawn** [huserben/TfsExtensions#90]
Steps:
1. Download `benjhuser.tfs-extensions-build-tasks-3.0.2.vsix` from the marketplace.
2. Install in the on premise TFS (in my case, TFS 2017 Update 1)

Expected result:
- Installation succeeds

Actual result:
Error message: 
>Extension package contains invalid character(16, 40). Error: XML Document- 'public' is not a valid value for global::Microsoft.VisualStudio.Services.Gallery.WebApi.PublishedExtensionFlags.

![image](https://user-images.githubusercontent.com/1705112/44195858-9aacef80-a13a-11e8-8b7a-49d30b82134f.png)

Likely cause:
extension.vsixmanifest contents:
![image](https://user-images.githubusercontent.com/1705112/44196055-26bf1700-a13b-11e8-9f05-38937eed9820.png)

I couldn't locate this file in the repo, hence no PR

**Comment by huserben** [comment]
Hi @jawn 

thank you for the input.
I think the file is created out of the [vss-extension.json](https://github.com/huserben/TfsExtensions/blob/master/BuildTasks/vss-extension.json)

I will change it and then update the extension.
However, upon uploading in the marketplace the extension is verified, and I would assume at least there it could/should be detected, I wonder whether we should check with Microsoft if we can detect this before it gets published. As I don't have an on Prem TFS I sadly cannot really easily test these cases.

**Comment by huserben** [comment]
@jawn 
I uploaded a new version now where the Public flag is written in uppercase.
Do you mind give it another try and let me know whether it worked or not?

**Comment by jawn** [comment]
@huserben 
Tested with version 3.0.3 and I get a different error message:
> The task.json file was not found in contribution triggerbuildtask.

**Comment by huserben** [comment]
hmm i quickly checked the package (one can simply unzip it as the vsix is nothing else but a zip file) and for every task in every version a task.json is there.
I wonder if maybe your version of TFS is not supporting to have multiple versions of one task in the same extension.
I could try to create a custom package for you if you are willing to download it from another source than the marketplace. I assume you'll need the vsix file in the end to upload it to TFS?

**Comment by jawn** [comment]
That worked!

**Comment by huserben** [comment]
Ok very good, thanks for your input @jawn 

I will try in that case from now on to create a dedicated package containing only the newest versions, as there seems to be a problem with (older?) versions of TFS with the multiversion packages.
I shall accordingly update the docs so other people hopefully don't run into the problem.

As well I'll try to check with Microsoft whether this is a known problem for on Prem TFS versions or its just specific to 2017 Update 1, so we would known when you could actually go back and use the "official" version from the Marketplace

**Comment by huserben** [comment]
Hi @jawn 
the newest version of the package will from now on be available under https://github.com/huserben/TfsExtensions/tree/master/BuildTasks/Releases/singleversion in a version that only includes the newest versions of the tasks.

Futhermore I updated the Supported TFS section in the [Overview](https://github.com/huserben/TfsExtensions/blob/master/BuildTasks/overview.md#supported-tfs-versions) that is as well displayed on the marketplace with the information about possible problems with TFS.

Thanks again for that input.
