### ISSUE TITLE
Failing to queue build for refs/heads/master

### ISSUE THREAD

**Issue by sanderaernouts** [huserben/TfsExtensions#92]
According to your documentation both here on github and in the task tooltip `refs/heads/master` should be used to queue a build on master. However this does not seem to work. When I queue it for `master` it works as expected:
![image](https://user-images.githubusercontent.com/6184673/44468616-e6253900-a625-11e8-958a-cbaccdaecaac.png)

![image](https://user-images.githubusercontent.com/6184673/44468594-d7d71d00-a625-11e8-996e-04c9044a552e.png)

I get this error in the `Get Sources` task on VSTS:
![image](https://user-images.githubusercontent.com/6184673/44468694-18cf3180-a626-11e8-9e9e-94cf0828418d.png)

**Comment by huserben** [comment]
Hi @sanderaernouts 

thanks for your feedback.
Are you using the version 3 of the task or are you still on version 2?

It could be that due to the refactoring done in version 3 this has changed and gone unnoticed so far.

**Comment by sanderaernouts** [comment]
Hi @huserben 
I am using `3.*` of the tasks and the builds are queued in the same VSTS project.

**Comment by huserben** [comment]
@sanderaernouts 
Ok, thanks for the info. Then this has changed due to the new implementation and is now simpler. I will update the docs accordingly. Thank you for the feedback.

@dwhearn 
I think you're facing a different problem, please open a  new issue describing what exactly is failing and in what environment you are (TFS including Version or VSTS, which version of the task, configuration, logs of the task)

**Comment by sanderaernouts** [comment]
@huserben happy to contribute :). Great tasks extension by the way:+1:! They really come in handy when you need to queue a build and require it's artifacts somewhere further down in your build.

**Comment by huserben** [comment]
Hi @sanderaernouts 

I uploaded a new version of the task which has the description fixed:
![grafik](https://user-images.githubusercontent.com/5486874/44617085-2ae6e500-a85d-11e8-9a52-4c8d4ad35937.png)

 As well I changed it in the [Overview](https://github.com/huserben/TfsExtensions/blob/master/BuildTasks/overview.md#use-same-source-branch) that is displayed on the marketplace:
![grafik](https://user-images.githubusercontent.com/5486874/44617096-5669cf80-a85d-11e8-8f58-0ad9276af799.png)

Thank you for your help. Please don't hesitate to raise another issue in case you run into a problem or you have an idea for an improvement.
