### ISSUE TITLE
Failing to queue build if in same VSTS project

### ISSUE THREAD

**Issue by dwhearn** [huserben/TfsExtensions#93]
After upgrading to the 3.* version of the 'Trigger Build' task, if the build being triggered is in the same VSTS team project (the 'True if the build to be triggered is defined within the same team project as this build' option is checked), then it will fail with the error message: '##[error]Could not find any Team project with name <MyTeamProjectName>'. Switching back to the 2.* version works correctly.

A similar problem exists for the 2.* version of the 'Wait for Builds to finish' task when waiting for builds to complete within the same VSTS team project. Switching back to the 1.* version works correctly.

Both tasks work correctly when the build being queued is in a different VSTS team project.

**Comment by huserben** [comment]
Hi

could you show me the log of any of the failing tasks, preferrably with the system.debug variable set to true.
As you're using VSTS its hard to judge what possibly goes wrong, as I use this myself and it worked without a problem so far. What kind of authentication are you using?

**Comment by dwhearn** [comment]
It was failing when using version 3.0.1, but is now working with version 3.0.3.
